import { describe, expect, it } from "vitest";
import { optimizePackageSet, optimizationScore, packageOptimizationMetrics, paretoFrontier, rankComponents, resolveRankingWeights } from "../optimization";
import { rankPackages } from "../ranking";
import type { NormalizedComponent, SupplierRegistration, TripRequirements } from "../types";

const req:TripRequirements={origin:"DEL",destinations:["IST"],departFrom:"2026-10-10",returnBy:"2026-10-20",adults:2,children:0,luxuryLevel:5,interests:["museum"]};
const reg=new Map<string,SupplierRegistration>([["s1",{supplierKey:"s1",kinds:["flight","stay","activity"],capabilities:["search","revalidate","book"],readiness:"production",reliability:0.95}],["s2",{supplierKey:"s2",kinds:["flight","stay","activity"],capabilities:["search","revalidate","book"],readiness:"production",reliability:0.6}]]);
const c=(id:string,supplierKey:string,kind:NormalizedComponent["kind"],title:string,place="IST"):NormalizedComponent=>({id,kind,supplierKey,externalId:id,title,start:{at:"2026-10-11T10:00:00Z",timezone:"Europe/Istanbul",place},end:{at:"2026-10-11T12:00:00Z",timezone:"Europe/Istanbul",place},net:{amount:100,currency:"EUR"},taxes:{amount:10,currency:"EUR"},cancellation:{refundable:true},quality:5,revalidatedAt:"2026-10-03T00:00:00Z"});

describe("Phase 7 ranking and optimization",()=>{
 it("normalizes ranking weights",()=>{const w=resolveRankingWeights({weights:{price:2,margin:0}});expect(Object.values(w).reduce((a,b)=>a+b,0)).toBeCloseTo(1);expect(w.price).toBeGreaterThan(w.margin);});
 it("ranks complete packages using geography, time, margin and preference",()=>{const good=[c("g1","s1","stay","Luxury museum stay")];const weak=[c("g2","s2","stay","Generic stay","PAR")];const a=rankPackages([{id:"good",items:good,total:1000,marginAmount:200},{id:"weak",items:weak,total:900,marginAmount:20}],req,reg,{interests:["museum"]});expect(a[0]?.id).toBe("good");expect(a[0]?.factors.map(x=>x.factor)).toEqual(["Itinerary feasibility","Quality / luxury fit","Price","Within budget","Cancellation flexibility","Supplier reliability","Geographic fit","Time / convenience","Commercial margin","Customer preference fit"]);});
 it("propagates profile weights into component ranking",()=>{const ranked=rankComponents([c("a","s1","activity","Generic transfer"),c("b","s2","activity","Museum visit")],req,reg,{interests:["museum"],weights:{preference:0.9,luxury:0.05,reliability:0.03,geography:0.02}});expect(ranked[0]?.id).toBe("b");});
 it("supports component-level ranking without exposing supplier identity",()=>{const ranked=rankComponents([c("a","s2","activity","City museum visit"),c("b","s1","activity","City transfer")],req,reg,{interests:["museum"]});expect(ranked[0]?.id).toBe("a");});
 it("computes deterministic optimization metrics",()=>{const m=packageOptimizationMetrics({id:"x",items:[c("x1","s1","stay","Museum stay")],total:200,marginAmount:50},req,reg,{interests:["museum"]});expect(m.geography).toBe(1);expect(m.margin).toBe(0.25);expect(m.preference).toBeGreaterThan(0.5);});
})
 it("builds a deterministic Pareto frontier",()=>{const a={id:"a",items:[c("a1","s1","stay","Museum stay")],total:100,marginAmount:30};const b={id:"b",items:[c("b1","s1","stay","Generic stay","IST")],total:120,marginAmount:40};const frontier=paretoFrontier([a,b],req,reg,{interests:["museum"]});expect(frontier.map(x=>x.id).sort()).toEqual(["a","b"]);});
 it("exposes Pareto optimization on ranked packages",()=>{const a={id:"a",items:[c("a1","s1","stay","Museum stay")],total:100,marginAmount:30};const b={id:"b",items:[c("b1","s1","stay","Generic stay")],total:120,marginAmount:40};const ranked=rankPackages([a,b],req,reg,{interests:["museum"]});expect(ranked.every(x=>x.optimizationMetrics)).toBe(true);expect(ranked.filter(x=>x.paretoOptimal).map(x=>x.id).sort()).toEqual(["a","b"]);});
 it("uses the ranking profile when ordering the optimized shortlist",()=>{const items=[{id:"cheap",items:[c("cheap1","s1","stay","Generic stay")],total:100,marginAmount:5},{id:"preferred",items:[c("preferred1","s1","stay","Museum stay")],total:160,marginAmount:20}];const profile={interests:["museum"],weights:{preference:0.8,price:0.1,geography:0.05,time:0.025,margin:0.025}};expect(optimizationScore(items[1],items,req,reg,profile)).toBeGreaterThan(optimizationScore(items[0],items,req,reg,profile));expect(optimizePackageSet(items,req,reg,1,profile).map(x=>x.id)).toEqual(["preferred"]);});
 it("returns a stable optimized shortlist",()=>{const items=[1,2,3,4].map(n=>({id:"p"+n,items:[c("p"+n,"s1","stay",n===1?"Museum stay":"Stay "+n)],total:100+n*10,marginAmount:n*5}));const selected=optimizePackageSet(items,req,reg,3,{interests:["museum"]});expect(selected).toHaveLength(3);expect(new Set(selected.map(x=>x.id)).size).toBe(3);});
;