import { describe, expect, it } from "vitest";
import { authorizeNetworkRequest, buildIntelligenceSnapshot, canCommitOffer, normalizeOffers, rankDemand, upsertGraphNodes, validateGraphEdges } from "../global-travel-intelligence";
const evidence=[{source:"official",observedAt:"2026-10-03T00:00:00.000Z",confidence:0.95}]; const now=new Date("2026-10-03T01:00:00.000Z");
describe("Phase 16 — Global Travel Commerce Intelligence Network",()=>{
it("deduplicates canonical graph nodes deterministically",()=>{const nodes=upsertGraphNodes([{id:"2",type:"destination",canonicalKey:"Paris",attributes:{}},{id:"1",type:"destination",canonicalKey:"paris",attributes:{}},{id:"3",type:"supplier",canonicalKey:"Supplier-A",attributes:{}}]);expect(nodes).toHaveLength(2);expect(nodes.find(n=>n.type==="destination")?.id).toBe("1");});
it("requires graph edges to reference valid nodes and evidence",()=>{const nodes=[{id:"d1",type:"destination" as const,canonicalKey:"paris",attributes:{}}];expect(()=>validateGraphEdges(nodes,[{id:"e1",fromNodeId:"d1",toNodeId:"d1",type:"located_in",evidence}])).not.toThrow();});
it("normalizes live inventory without fabricating unavailable offers",()=>{const offers=normalizeOffers([{id:"a",supplierKey:"s1",productId:"p1",currency:"EUR",total:900,available:true,priceVersion:"v1",validUntil:"2026-10-03T02:00:00.000Z",evidence},{id:"b",supplierKey:"s1",productId:"p1",currency:"EUR",total:850,available:false,priceVersion:"v2",validUntil:"2026-10-03T02:30:00.000Z",evidence}],now);expect(offers).toHaveLength(1);expect(offers[0].id).toBe("b");expect(canCommitOffer(offers[0],now)).toBe(false);});
it("builds an evidence-backed intelligence snapshot",()=>{const snapshot=buildIntelligenceSnapshot("paris",[{id:"c1",kind:"condition",subjectId:"paris",value:{weather:"clear"},evidence,capturedAt:now.toISOString()}],[{id:"o1",supplierKey:"s1",productId:"p1",currency:"EUR",total:100,available:true,priceVersion:"v1",validUntil:"2026-10-03T02:00:00.000Z",evidence}],undefined,now);expect(snapshot.inventory).toHaveLength(1);expect(snapshot.conditions).toHaveLength(1);});
it("ranks demand deterministically",()=>{const ranked=rankDemand([{destinationId:"b",score:0.4,direction:"rising",observedAt:now.toISOString(),evidence},{destinationId:"a",score:0.9,direction:"stable",observedAt:now.toISOString(),evidence}]);expect(ranked[0].destinationId).toBe("a");});
it("blocks autonomous mutation unless explicitly enabled",()=>{const request={requestId:"r1",tenantId:"t1",channel:"agent" as const,capability:"book" as const,subjectIds:["offer-1"],requestedAt:now.toISOString(),policy:{allowedCapabilities:["book"] as const,maxQuoteAgeSeconds:300,requireEvidence:true,requireFreshInventoryForCommit:true,allowAutonomousMutation:false}};const decision=authorizeNetworkRequest(request,now);expect(decision.allowed).toBe(false);expect(decision.requiresRevalidation).toBe(true);});
it("allows read-only intelligence within a fresh policy window",()=>{const request={requestId:"r2",tenantId:"t1",channel:"enterprise" as const,capability:"compare" as const,subjectIds:["destination-1"],requestedAt:now.toISOString(),policy:{allowedCapabilities:["compare"] as const,maxQuoteAgeSeconds:300,requireEvidence:true,requireFreshInventoryForCommit:true,allowAutonomousMutation:false}};expect(authorizeNetworkRequest(request,now).allowed).toBe(true);});
});