// Worldway aircraft catalogue — model facts transcribed from the cited Wikipedia specification
// tables (which cite manufacturer data), retrieved 2026-09-29. Photos: Wikimedia Commons files whose
// licence permits commercial use, shown only when the photo depicts that exact model; otherwise the
// Worldway placeholder is used. No prices live here — pricing is live-only (see jet-pricing).

export type AircraftCategoryName = "Very Light Jet" | "Light Jet" | "Midsize Jet" | "Super Midsize Jet" | "Heavy Jet" | "Ultra Long Range" | "Turboprop" | "VIP Airliner";
export type AircraftPhoto = { url: string; file: string; page: string; license: string; licenseUrl: string; artist: string };
export type CatalogueAircraft = { slug: string; name: string; manufacturer: string; category: AircraftCategoryName; maxPassengers: number; typicalSeating: string | null; rangeNm: number | null; cruise: string | null; maxSpeed: string | null; source: { title: string; url: string }; photo: AircraftPhoto | null };

export const AIRCRAFT_CATALOGUE: CatalogueAircraft[] = [
  {"slug": "gulfstream-g650", "name": "Gulfstream G650", "manufacturer": "Gulfstream Aerospace", "category": "Ultra Long Range", "maxPassengers": 19, "typicalSeating": null, "rangeNm": 7000, "cruise": "Mach 0.85–0.90", "maxSpeed": "Mach 0.925 (MMO)", "source": {"title": "Wikipedia — Gulfstream G650/G700/G800", "url": "https://en.wikipedia.org/wiki/Gulfstream_G650/G700/G800"}, "photo": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d6/G-ULFS_Gulfstream_G650_CVT_05-05-16_%2827046023031%29_%28cropped%29.jpg/1280px-G-ULFS_Gulfstream_G650_CVT_05-05-16_%2827046023031%29_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", "file": "G-ULFS Gulfstream G650 CVT 05-05-16 (27046023031) (cropped).jpg", "page": "https://commons.wikimedia.org/wiki/File:G-ULFS_Gulfstream_G650_CVT_05-05-16_(27046023031)_(cropped).jpg", "license": "CC BY-SA 2.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0", "artist": "Rob Hodgkins"}},
  {"slug": "gulfstream-g650er", "name": "Gulfstream G650ER", "manufacturer": "Gulfstream Aerospace", "category": "Ultra Long Range", "maxPassengers": 19, "typicalSeating": null, "rangeNm": 7500, "cruise": "Mach 0.85–0.90", "maxSpeed": "Mach 0.925 (MMO)", "source": {"title": "Wikipedia — Gulfstream G650/G700/G800", "url": "https://en.wikipedia.org/wiki/Gulfstream_G650/G700/G800"}, "photo": null},
  {"slug": "gulfstream-g700", "name": "Gulfstream G700", "manufacturer": "Gulfstream Aerospace", "category": "Ultra Long Range", "maxPassengers": 19, "typicalSeating": null, "rangeNm": 7750, "cruise": "Mach 0.85–0.90", "maxSpeed": "Mach 0.935 (MMO)", "source": {"title": "Wikipedia — Gulfstream G650/G700/G800", "url": "https://en.wikipedia.org/wiki/Gulfstream_G650/G700/G800"}, "photo": null},
  {"slug": "gulfstream-g800", "name": "Gulfstream G800", "manufacturer": "Gulfstream Aerospace", "category": "Ultra Long Range", "maxPassengers": 19, "typicalSeating": null, "rangeNm": 8200, "cruise": "Mach 0.85–0.90", "maxSpeed": "Mach 0.935 (MMO)", "source": {"title": "Wikipedia — Gulfstream G650/G700/G800", "url": "https://en.wikipedia.org/wiki/Gulfstream_G650/G700/G800"}, "photo": null},
  {"slug": "gulfstream-g600", "name": "Gulfstream G600", "manufacturer": "Gulfstream Aerospace", "category": "Heavy Jet", "maxPassengers": 19, "typicalSeating": null, "rangeNm": 6600, "cruise": "Mach 0.85–0.90", "maxSpeed": "Mach 0.925 (MMO)", "source": {"title": "Wikipedia — Gulfstream G400/G500/G600", "url": "https://en.wikipedia.org/wiki/Gulfstream_G400/G500/G600"}, "photo": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Gulfstream_G600.jpg/1280px-Gulfstream_G600.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", "file": "Gulfstream G600.jpg", "page": "https://commons.wikimedia.org/wiki/File:Gulfstream_G600.jpg", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "artist": "Dontenphotography"}},
  {"slug": "gulfstream-g500", "name": "Gulfstream G500", "manufacturer": "Gulfstream Aerospace", "category": "Heavy Jet", "maxPassengers": 19, "typicalSeating": null, "rangeNm": 5300, "cruise": "Mach 0.85–0.90", "maxSpeed": "Mach 0.925 (MMO)", "source": {"title": "Wikipedia — Gulfstream G400/G500/G600", "url": "https://en.wikipedia.org/wiki/Gulfstream_G400/G500/G600"}, "photo": null},
  {"slug": "gulfstream-g280", "name": "Gulfstream G280", "manufacturer": "Gulfstream Aerospace", "category": "Super Midsize Jet", "maxPassengers": 10, "typicalSeating": "10 in executive seating", "rangeNm": 3600, "cruise": "459 kt", "maxSpeed": "Mach 0.84", "source": {"title": "Wikipedia — Gulfstream G280", "url": "https://en.wikipedia.org/wiki/Gulfstream_G280"}, "photo": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/IAI_Gulfstream_G280_-_Gulfstrem_Aerospace_%2818701234531%29.jpg/1280px-IAI_Gulfstream_G280_-_Gulfstrem_Aerospace_%2818701234531%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", "file": "IAI Gulfstream G280 - Gulfstrem Aerospace (18701234531).jpg", "page": "https://commons.wikimedia.org/wiki/File:IAI_Gulfstream_G280_-_Gulfstrem_Aerospace_(18701234531).jpg", "license": "CC BY-SA 2.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0", "artist": "flybyeigenheer"}},
  {"slug": "bombardier-global-7500", "name": "Bombardier Global 7500", "manufacturer": "Bombardier", "category": "Ultra Long Range", "maxPassengers": 19, "typicalSeating": null, "rangeNm": 7700, "cruise": "Mach 0.85 typical · Mach 0.90 high-speed", "maxSpeed": "Mach 0.925 (MMO)", "source": {"title": "Wikipedia — Bombardier Global 7500", "url": "https://en.wikipedia.org/wiki/Bombardier_Global_7500"}, "photo": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/N182QS-Global7500-120823.png/1280px-N182QS-Global7500-120823.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", "file": "N182QS-Global7500-120823.png", "page": "https://commons.wikimedia.org/wiki/File:N182QS-Global7500-120823.png", "license": "CC0", "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en", "artist": "KeepPhlyingHigh"}},
  {"slug": "bombardier-global-8000", "name": "Bombardier Global 8000", "manufacturer": "Bombardier", "category": "Ultra Long Range", "maxPassengers": 19, "typicalSeating": null, "rangeNm": 8000, "cruise": "Mach 0.85 typical · up to Mach 0.92", "maxSpeed": "Mach 0.95 (MMO)", "source": {"title": "Wikipedia — Bombardier Global 7500", "url": "https://en.wikipedia.org/wiki/Bombardier_Global_7500"}, "photo": null},
  {"slug": "bombardier-challenger-300", "name": "Bombardier Challenger 300", "manufacturer": "Bombardier", "category": "Super Midsize Jet", "maxPassengers": 16, "typicalSeating": "8–9 in standard layouts", "rangeNm": 3100, "cruise": "Mach 0.80 (459 kt)", "maxSpeed": "Mach 0.83 (477 kt)", "source": {"title": "Wikipedia — Bombardier Challenger 300", "url": "https://en.wikipedia.org/wiki/Bombardier_Challenger_300"}, "photo": {"url": "https://upload.wikimedia.org/wikipedia/commons/2/22/Bombardier_BD-100-1A10_Challenger_300_AN1704544.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", "file": "Bombardier BD-100-1A10 Challenger 300 AN1704544.jpg", "page": "https://commons.wikimedia.org/wiki/File:Bombardier_BD-100-1A10_Challenger_300_AN1704544.jpg", "license": "CC BY-SA 3.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0", "artist": "Igor Dvurekov"}},
  {"slug": "bombardier-challenger-350", "name": "Bombardier Challenger 350", "manufacturer": "Bombardier", "category": "Super Midsize Jet", "maxPassengers": 16, "typicalSeating": "8–9 in standard layouts", "rangeNm": 3200, "cruise": "Mach 0.80 (459 kt)", "maxSpeed": "Mach 0.83 (477 kt)", "source": {"title": "Wikipedia — Bombardier Challenger 300", "url": "https://en.wikipedia.org/wiki/Bombardier_Challenger_300"}, "photo": null},
  {"slug": "learjet-75", "name": "Learjet 75", "manufacturer": "Bombardier", "category": "Light Jet", "maxPassengers": 9, "typicalSeating": "8 + 1", "rangeNm": 2040, "cruise": "465 kt", "maxSpeed": null, "source": {"title": "Wikipedia — Learjet 70/75", "url": "https://en.wikipedia.org/wiki/Learjet_70/75"}, "photo": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/G-ZNTH_Learjet_75_LJ75_c_n_45-540_-_BZE_%2846212773245%29.jpg/1280px-G-ZNTH_Learjet_75_LJ75_c_n_45-540_-_BZE_%2846212773245%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", "file": "G-ZNTH Learjet 75 LJ75 c n 45-540 - BZE (46212773245).jpg", "page": "https://commons.wikimedia.org/wiki/File:G-ZNTH_Learjet_75_LJ75_c_n_45-540_-_BZE_(46212773245).jpg", "license": "CC BY-SA 2.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0", "artist": "Markus Eigenheer from Genève, Schweiz"}},
  {"slug": "dassault-falcon-7x", "name": "Dassault Falcon 7X", "manufacturer": "Dassault Aviation", "category": "Heavy Jet", "maxPassengers": 16, "typicalSeating": "12–16", "rangeNm": 5950, "cruise": "Mach 0.80", "maxSpeed": "Mach 0.90", "source": {"title": "Wikipedia — Dassault Falcon 7X", "url": "https://en.wikipedia.org/wiki/Dassault_Falcon_7X"}, "photo": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/99/VQ-BGG%40PEK_%2820170314150921%29.jpg/1280px-VQ-BGG%40PEK_%2820170314150921%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", "file": "VQ-BGG@PEK (20170314150921).jpg", "page": "https://commons.wikimedia.org/wiki/File:VQ-BGG@PEK_(20170314150921).jpg", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "artist": "N509FZ"}},
  {"slug": "dassault-falcon-8x", "name": "Dassault Falcon 8X", "manufacturer": "Dassault Aviation", "category": "Ultra Long Range", "maxPassengers": 16, "typicalSeating": "12–16", "rangeNm": 6450, "cruise": "Mach 0.80", "maxSpeed": "Mach 0.90", "source": {"title": "Wikipedia — Dassault Falcon 7X", "url": "https://en.wikipedia.org/wiki/Dassault_Falcon_7X"}, "photo": null},
  {"slug": "dassault-falcon-2000", "name": "Dassault Falcon 2000", "manufacturer": "Dassault Aviation", "category": "Super Midsize Jet", "maxPassengers": 10, "typicalSeating": null, "rangeNm": 4000, "cruise": null, "maxSpeed": "Mach 0.85–0.862", "source": {"title": "Wikipedia — Dassault Falcon 2000", "url": "https://en.wikipedia.org/wiki/Dassault_Falcon_2000"}, "photo": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/20130519190713%212010-07-15_Falcon2000_private_N671WM_EDDF_01_%28cropped%29.jpg/1280px-20130519190713%212010-07-15_Falcon2000_private_N671WM_EDDF_01_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", "file": "20130519190713!2010-07-15 Falcon2000 private N671WM EDDF 01 (cropped).jpg", "page": "https://commons.wikimedia.org/wiki/File:20130519190713!2010-07-15_Falcon2000_private_N671WM_EDDF_01_(cropped).jpg", "license": "CC BY-SA 3.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0", "artist": "Wo st 01 at German Wikipedia"}},
  {"slug": "dassault-falcon-900", "name": "Dassault Falcon 900", "manufacturer": "Dassault Aviation", "category": "Heavy Jet", "maxPassengers": 19, "typicalSeating": null, "rangeNm": 3996, "cruise": "950 km/h", "maxSpeed": "Mach 0.84–0.87", "source": {"title": "Wikipedia — Dassault Falcon 900", "url": "https://en.wikipedia.org/wiki/Dassault_Falcon_900"}, "photo": {"url": "https://upload.wikimedia.org/wikipedia/commons/5/58/Spanish_Air_Force_Dassault_Falcon_900B.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", "file": "Spanish Air Force Dassault Falcon 900B.jpg", "page": "https://commons.wikimedia.org/wiki/File:Spanish_Air_Force_Dassault_Falcon_900B.jpg", "license": "CC BY 3.0", "licenseUrl": "https://creativecommons.org/licenses/by/3.0", "artist": "Luc Verkuringen"}},
  {"slug": "embraer-phenom-100", "name": "Embraer Phenom 100", "manufacturer": "Embraer", "category": "Very Light Jet", "maxPassengers": 7, "typicalSeating": "4–5 standard", "rangeNm": 1178, "cruise": "750 km/h", "maxSpeed": "Mach 0.70", "source": {"title": "Wikipedia — Embraer Phenom 100", "url": "https://en.wikipedia.org/wiki/Embraer_Phenom_100"}, "photo": {"url": "https://upload.wikimedia.org/wikipedia/commons/f/f1/Embraer_EMB-500_Phenom_100_AN1695056.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", "file": "Embraer EMB-500 Phenom 100 AN1695056.jpg", "page": "https://commons.wikimedia.org/wiki/File:Embraer_EMB-500_Phenom_100_AN1695056.jpg", "license": "GFDL 1.2", "licenseUrl": "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html", "artist": "Alan Lebeda"}},
  {"slug": "embraer-phenom-300", "name": "Embraer Phenom 300", "manufacturer": "Embraer", "category": "Light Jet", "maxPassengers": 10, "typicalSeating": "6–8 standard", "rangeNm": 2010, "cruise": "839 km/h", "maxSpeed": "859 km/h", "source": {"title": "Wikipedia — Embraer Phenom 300", "url": "https://en.wikipedia.org/wiki/Embraer_Phenom_300"}, "photo": {"url": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Embraer_505_Phenom_300%2C_Aerojet_JP7625910.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", "file": "Embraer 505 Phenom 300, Aerojet JP7625910.jpg", "page": "https://commons.wikimedia.org/wiki/File:Embraer_505_Phenom_300,_Aerojet_JP7625910.jpg", "license": "GFDL 1.2", "licenseUrl": "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html", "artist": "Aktug Ates"}},
  {"slug": "embraer-legacy-500", "name": "Embraer Legacy 500", "manufacturer": "Embraer", "category": "Midsize Jet", "maxPassengers": 12, "typicalSeating": "8–12", "rangeNm": 3125, "cruise": "466 kt (high cruise)", "maxSpeed": "Mach 0.83", "source": {"title": "Wikipedia — Embraer Legacy 450/500 and Praetor 500/600", "url": "https://en.wikipedia.org/wiki/Embraer_Legacy_450/500_and_Praetor_500/600"}, "photo": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/41/PT-ZHY_Embraer_EMB550_Legacy500_E550_%2814272527752%29.jpg/1280px-PT-ZHY_Embraer_EMB550_Legacy500_E550_%2814272527752%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", "file": "PT-ZHY Embraer EMB550 Legacy500 E550 (14272527752).jpg", "page": "https://commons.wikimedia.org/wiki/File:PT-ZHY_Embraer_EMB550_Legacy500_E550_(14272527752).jpg", "license": "CC BY-SA 2.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0", "artist": "Markus Eigenheer from Genève"}},
  {"slug": "embraer-praetor-500", "name": "Embraer Praetor 500", "manufacturer": "Embraer", "category": "Midsize Jet", "maxPassengers": 9, "typicalSeating": "7–9", "rangeNm": 3340, "cruise": "466 kt (high cruise)", "maxSpeed": "Mach 0.83", "source": {"title": "Wikipedia — Embraer Legacy 450/500 and Praetor 500/600", "url": "https://en.wikipedia.org/wiki/Embraer_Legacy_450/500_and_Praetor_500/600"}, "photo": null},
  {"slug": "embraer-praetor-600", "name": "Embraer Praetor 600", "manufacturer": "Embraer", "category": "Super Midsize Jet", "maxPassengers": 12, "typicalSeating": "8–12", "rangeNm": 4018, "cruise": "466 kt (high cruise)", "maxSpeed": "Mach 0.83", "source": {"title": "Wikipedia — Embraer Legacy 450/500 and Praetor 500/600", "url": "https://en.wikipedia.org/wiki/Embraer_Legacy_450/500_and_Praetor_500/600"}, "photo": null},
  {"slug": "embraer-lineage-1000", "name": "Embraer Lineage 1000", "manufacturer": "Embraer", "category": "VIP Airliner", "maxPassengers": 19, "typicalSeating": "13 typical", "rangeNm": 4500, "cruise": "472 kt", "maxSpeed": "Mach 0.82", "source": {"title": "Wikipedia — Embraer Lineage 1000", "url": "https://en.wikipedia.org/wiki/Embraer_Lineage_1000"}, "photo": {"url": "https://upload.wikimedia.org/wikipedia/commons/5/51/A6-AJH_%288830512064%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", "file": "A6-AJH (8830512064).jpg", "page": "https://commons.wikimedia.org/wiki/File:A6-AJH_(8830512064).jpg", "license": "CC BY 2.0", "licenseUrl": "https://creativecommons.org/licenses/by/2.0", "artist": "Mark Harkin"}},
  {"slug": "cessna-citation-longitude", "name": "Cessna Citation Longitude", "manufacturer": "Textron Aviation", "category": "Super Midsize Jet", "maxPassengers": 12, "typicalSeating": "8–12", "rangeNm": 3500, "cruise": "483 kt", "maxSpeed": null, "source": {"title": "Wikipedia — Cessna Citation Longitude", "url": "https://en.wikipedia.org/wiki/Cessna_Citation_Longitude"}, "photo": {"url": "https://upload.wikimedia.org/wikipedia/commons/b/bc/N336ML_%283_Nov_2023%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", "file": "N336ML (3 Nov 2023).jpg", "page": "https://commons.wikimedia.org/wiki/File:N336ML_(3_Nov_2023).jpg", "license": "CC0", "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en", "artist": "Dltl2010"}},
  {"slug": "cessna-citation-latitude", "name": "Cessna Citation Latitude", "manufacturer": "Textron Aviation", "category": "Midsize Jet", "maxPassengers": 9, "typicalSeating": null, "rangeNm": 2700, "cruise": "368 kt", "maxSpeed": "446 kt", "source": {"title": "Wikipedia — Cessna Citation Latitude", "url": "https://en.wikipedia.org/wiki/Cessna_Citation_Latitude"}, "photo": null},
  {"slug": "cessna-citation-sovereign", "name": "Cessna Citation Sovereign", "manufacturer": "Textron Aviation", "category": "Midsize Jet", "maxPassengers": 12, "typicalSeating": null, "rangeNm": 3200, "cruise": "460 kt", "maxSpeed": "Mach 0.80", "source": {"title": "Wikipedia — Cessna Citation Sovereign", "url": "https://en.wikipedia.org/wiki/Cessna_Citation_Sovereign"}, "photo": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Cessna_Citation_Sovereign_Rafael_Luiz_%2814725958464%29.jpg/1280px-Cessna_Citation_Sovereign_Rafael_Luiz_%2814725958464%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", "file": "Cessna Citation Sovereign Rafael Luiz (14725958464).jpg", "page": "https://commons.wikimedia.org/wiki/File:Cessna_Citation_Sovereign_Rafael_Luiz_(14725958464).jpg", "license": "CC BY-SA 2.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0", "artist": "Rafael Luiz Canossa"}},
  {"slug": "cessna-citation-xls-plus", "name": "Cessna Citation XLS+", "manufacturer": "Textron Aviation", "category": "Midsize Jet", "maxPassengers": 9, "typicalSeating": null, "rangeNm": 1858, "cruise": null, "maxSpeed": null, "source": {"title": "Wikipedia — Cessna Citation Excel", "url": "https://en.wikipedia.org/wiki/Cessna_Citation_Excel"}, "photo": null},
  {"slug": "cessna-citation-cj3-plus", "name": "Cessna Citation CJ3+", "manufacturer": "Textron Aviation", "category": "Light Jet", "maxPassengers": 9, "typicalSeating": null, "rangeNm": 2040, "cruise": "416 kt (max cruise)", "maxSpeed": null, "source": {"title": "Wikipedia — Cessna CitationJet/M2", "url": "https://en.wikipedia.org/wiki/Cessna_CitationJet/M2"}, "photo": null},
  {"slug": "cessna-citation-cj4", "name": "Cessna Citation CJ4", "manufacturer": "Textron Aviation", "category": "Light Jet", "maxPassengers": 10, "typicalSeating": null, "rangeNm": 2165, "cruise": "451 kt (max cruise)", "maxSpeed": null, "source": {"title": "Wikipedia — Cessna CitationJet/M2", "url": "https://en.wikipedia.org/wiki/Cessna_CitationJet/M2"}, "photo": null},
  {"slug": "hondajet", "name": "Honda HA-420 HondaJet", "manufacturer": "Honda Aircraft Company", "category": "Very Light Jet", "maxPassengers": 6, "typicalSeating": "4–5 typical", "rangeNm": null, "cruise": "422 kt at FL300", "maxSpeed": null, "source": {"title": "Wikipedia — Honda HA-420 HondaJet", "url": "https://en.wikipedia.org/wiki/Honda_HA-420_HondaJet"}, "photo": {"url": "https://upload.wikimedia.org/wikipedia/commons/2/23/HondaJet_Ryabtsev.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", "file": "HondaJet Ryabtsev.jpg", "page": "https://commons.wikimedia.org/wiki/File:HondaJet_Ryabtsev.jpg", "license": "GFDL 1.2", "licenseUrl": "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html", "artist": "Sergey Ryabtsev"}},
  {"slug": "pilatus-pc-24", "name": "Pilatus PC-24", "manufacturer": "Pilatus Aircraft", "category": "Light Jet", "maxPassengers": 10, "typicalSeating": null, "rangeNm": 2000, "cruise": "440 kt", "maxSpeed": null, "source": {"title": "Wikipedia — Pilatus PC-24", "url": "https://en.wikipedia.org/wiki/Pilatus_PC-24"}, "photo": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cb/Pilatus_PC-24%2C_P01%2C_HB-VXA_%2818743050229%29_%28cropped%29.jpg/1280px-Pilatus_PC-24%2C_P01%2C_HB-VXA_%2818743050229%29_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", "file": "Pilatus PC-24, P01, HB-VXA (18743050229) (cropped).jpg", "page": "https://commons.wikimedia.org/wiki/File:Pilatus_PC-24,_P01,_HB-VXA_(18743050229)_(cropped).jpg", "license": "CC BY-SA 2.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0", "artist": "Stephan Widmer"}},
  {"slug": "pilatus-pc-12", "name": "Pilatus PC-12", "manufacturer": "Pilatus Aircraft", "category": "Turboprop", "maxPassengers": 9, "typicalSeating": "6–9", "rangeNm": 1845, "cruise": "528 km/h", "maxSpeed": null, "source": {"title": "Wikipedia — Pilatus PC-12", "url": "https://en.wikipedia.org/wiki/Pilatus_PC-12"}, "photo": {"url": "https://upload.wikimedia.org/wikipedia/commons/8/89/Pilatus_PC-12-45%2C_Royal_Flying_Doctor_Service_AN0636290.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", "file": "Pilatus PC-12-45, Royal Flying Doctor Service AN0636290.jpg", "page": "https://commons.wikimedia.org/wiki/File:Pilatus_PC-12-45,_Royal_Flying_Doctor_Service_AN0636290.jpg", "license": "GFDL 1.2", "licenseUrl": "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html", "artist": "Chris Finney"}},
];

export const AIRCRAFT_CATEGORY_ORDER: AircraftCategoryName[] = ["Very Light Jet", "Turboprop", "Light Jet", "Midsize Jet", "Super Midsize Jet", "Heavy Jet", "Ultra Long Range", "VIP Airliner"];

export function aircraftBySlug(slug: string): CatalogueAircraft | undefined {
  return AIRCRAFT_CATALOGUE.find((a) => a.slug === slug);
}
