// GENERATED from OurAirports (public domain, davidmegginson.github.io/ourairports-data) on 2026-09-29.
// Airport identity/coordinates are source data; `city` is a Worldway display label.
// Distances are great-circle (haversine) in nautical miles. No prices live here.

export type JetAirport = { iata: string; icao: string; name: string; city: string; country: string; lat: number; lon: number };
export type JetRoute = { slug: string; from: string; to: string; group: "india" | "global"; distanceNm: number };

export const JET_AIRPORTS: Record<string, JetAirport> = {
  ACK: {"iata": "ACK", "icao": "KACK", "name": "Nantucket Memorial Airport", "city": "Nantucket", "country": "United States", "lat": 41.2531, "lon": -70.0602},
  AIP: {"iata": "AIP", "icao": "VIAX", "name": "Adampur Airport", "city": "Jalandhar (Adampur)", "country": "India", "lat": 31.4338, "lon": 75.7588},
  AKL: {"iata": "AKL", "icao": "NZAA", "name": "Auckland International Airport", "city": "Auckland", "country": "New Zealand", "lat": -37.012, "lon": 174.7863},
  AMD: {"iata": "AMD", "icao": "VAAH", "name": "Sardar Vallabh Patel International Airport", "city": "Ahmedabad", "country": "India", "lat": 23.0772, "lon": 72.6347},
  ASE: {"iata": "ASE", "icao": "KASE", "name": "Aspen-Pitkin County Airport (Sardy Field)", "city": "Aspen", "country": "United States", "lat": 39.2232, "lon": -106.869},
  ATH: {"iata": "ATH", "icao": "LGAV", "name": "Athens Eleftherios Venizelos International Airport", "city": "Athens", "country": "Greece", "lat": 37.9364, "lon": 23.9445},
  ATQ: {"iata": "ATQ", "icao": "VIAR", "name": "Sri Guru Ram Das Ji International Airport", "city": "Amritsar", "country": "India", "lat": 31.7096, "lon": 74.7973},
  BKK: {"iata": "BKK", "icao": "VTBS", "name": "Suvarnabhumi Airport", "city": "Bangkok", "country": "Thailand", "lat": 13.6811, "lon": 100.747},
  BLR: {"iata": "BLR", "icao": "VOBL", "name": "Kempegowda International Airport Bengaluru", "city": "Bengaluru", "country": "India", "lat": 13.1979, "lon": 77.7063},
  BOM: {"iata": "BOM", "icao": "VABB", "name": "Chhatrapati Shivaji Maharaj International Airport", "city": "Mumbai", "country": "India", "lat": 19.0887, "lon": 72.8679},
  CCU: {"iata": "CCU", "icao": "VECC", "name": "Netaji Subhash Chandra Bose International Airport", "city": "Kolkata", "country": "India", "lat": 22.654, "lon": 88.4476},
  COK: {"iata": "COK", "icao": "VOCI", "name": "Cochin International Airport", "city": "Kochi", "country": "India", "lat": 10.151, "lon": 76.4008},
  CPT: {"iata": "CPT", "icao": "FACT", "name": "Cape Town International Airport", "city": "Cape Town", "country": "South Africa", "lat": -33.974, "lon": 18.6043},
  DAL: {"iata": "DAL", "icao": "KDAL", "name": "Dallas Love Field", "city": "Dallas (Love Field)", "country": "United States", "lat": 32.8448, "lon": -96.8477},
  DED: {"iata": "DED", "icao": "VIDN", "name": "Dehradun Jolly Grant Airport", "city": "Dehradun", "country": "India", "lat": 30.1892, "lon": 78.1767},
  DEL: {"iata": "DEL", "icao": "VIDP", "name": "Indira Gandhi International Airport", "city": "New Delhi", "country": "India", "lat": 28.5556, "lon": 77.0952},
  DJT: {"iata": "DJT", "icao": "KDJT", "name": "President Donald J. Trump International Airport", "city": "West Palm Beach", "country": "United States", "lat": 26.6832, "lon": -80.0956},
  DOH: {"iata": "DOH", "icao": "OTHH", "name": "Hamad International Airport", "city": "Doha", "country": "Qatar", "lat": 25.2731, "lon": 51.6081},
  DPS: {"iata": "DPS", "icao": "WADD", "name": "Denpasar I Gusti Ngurah Rai International Airport", "city": "Bali (Denpasar)", "country": "Indonesia", "lat": -8.7484, "lon": 115.1671},
  DWC: {"iata": "DWC", "icao": "OMDW", "name": "Al Maktoum International Airport", "city": "Dubai (Al Maktoum)", "country": "United Arab Emirates", "lat": 24.8962, "lon": 55.1624},
  DXB: {"iata": "DXB", "icao": "OMDB", "name": "Dubai International Airport", "city": "Dubai", "country": "United Arab Emirates", "lat": 25.2498, "lon": 55.371},
  EGE: {"iata": "EGE", "icao": "KEGE", "name": "Eagle County Regional Airport", "city": "Vail (Eagle County)", "country": "United States", "lat": 39.6426, "lon": -106.918},
  FAB: {"iata": "FAB", "icao": "EGLF", "name": "Farnborough Airport", "city": "London (Farnborough)", "country": "United Kingdom", "lat": 51.2758, "lon": -0.7763},
  FAO: {"iata": "FAO", "icao": "LPFR", "name": "Faro - Gago Coutinho International Airport", "city": "Faro", "country": "Portugal", "lat": 37.0159, "lon": -7.9709},
  GIG: {"iata": "GIG", "icao": "SBGL", "name": "Rio de Janeiro Galeão – Tom Jobim International Airport", "city": "Rio de Janeiro", "country": "Brazil", "lat": -22.81, "lon": -43.2506},
  GOX: {"iata": "GOX", "icao": "VOGA", "name": "Manohar International Airport", "city": "Goa (Mopa)", "country": "India", "lat": 15.7443, "lon": 73.8606},
  GRU: {"iata": "GRU", "icao": "SBGR", "name": "São Paulo/Guarulhos–Governor André Franco Montoro International Airport", "city": "São Paulo", "country": "Brazil", "lat": -23.4313, "lon": -46.47},
  GVA: {"iata": "GVA", "icao": "LSGG", "name": "Geneva International Airport", "city": "Geneva", "country": "Switzerland", "lat": 46.2381, "lon": 6.109},
  HKG: {"iata": "HKG", "icao": "VHHH", "name": "Hong Kong International Airport", "city": "Hong Kong", "country": "Hong Kong", "lat": 22.3118, "lon": 113.9149},
  HND: {"iata": "HND", "icao": "RJTT", "name": "Tokyo Haneda International Airport", "city": "Tokyo (Haneda)", "country": "Japan", "lat": 35.5497, "lon": 139.787},
  HOU: {"iata": "HOU", "icao": "KHOU", "name": "William P. Hobby Airport", "city": "Houston (Hobby)", "country": "United States", "lat": 29.6453, "lon": -95.2768},
  HYD: {"iata": "HYD", "icao": "VOHS", "name": "Rajiv Gandhi International Airport", "city": "Hyderabad", "country": "India", "lat": 17.2313, "lon": 78.4299},
  IBZ: {"iata": "IBZ", "icao": "LEIB", "name": "Ibiza Airport", "city": "Ibiza", "country": "Spain", "lat": 38.8729, "lon": 1.3731},
  IXC: {"iata": "IXC", "icao": "VICG", "name": "Shaheed Bhagat Singh International Airport", "city": "Chandigarh", "country": "India", "lat": 30.6735, "lon": 76.7885},
  IXJ: {"iata": "IXJ", "icao": "VIJU", "name": "Jammu Airport", "city": "Jammu", "country": "India", "lat": 32.6888, "lon": 74.8382},
  IXL: {"iata": "IXL", "icao": "VILH", "name": "Leh Kushok Bakula Rimpochee Airport", "city": "Leh, Ladakh", "country": "India", "lat": 34.1359, "lon": 77.5465},
  JAI: {"iata": "JAI", "icao": "VIJP", "name": "Jaipur International Airport", "city": "Jaipur", "country": "India", "lat": 26.8242, "lon": 75.8122},
  JED: {"iata": "JED", "icao": "OEJN", "name": "King Abdulaziz International Airport", "city": "Jeddah", "country": "Saudi Arabia", "lat": 21.6802, "lon": 39.1574},
  JMK: {"iata": "JMK", "icao": "LGMK", "name": "Mykonos Island National Airport", "city": "Mykonos", "country": "Greece", "lat": 37.4351, "lon": 25.3481},
  JNB: {"iata": "JNB", "icao": "FAOR", "name": "O.R. Tambo International Airport", "city": "Johannesburg", "country": "South Africa", "lat": -26.1401, "lon": 28.2468},
  LAS: {"iata": "LAS", "icao": "KLAS", "name": "Harry Reid International Airport", "city": "Las Vegas", "country": "United States", "lat": 36.0834, "lon": -115.1518},
  LBG: {"iata": "LBG", "icao": "LFPB", "name": "Paris-Le Bourget International Airport", "city": "Paris (Le Bourget)", "country": "France", "lat": 48.9623, "lon": 2.4365},
  LTN: {"iata": "LTN", "icao": "EGGW", "name": "London Luton Airport", "city": "London (Luton)", "country": "United Kingdom", "lat": 51.8747, "lon": -0.3683},
  LUH: {"iata": "LUH", "icao": "VILD", "name": "Ludhiana Airport", "city": "Ludhiana", "country": "India", "lat": 30.8547, "lon": 75.9526},
  MAA: {"iata": "MAA", "icao": "VOMM", "name": "Chennai International Airport", "city": "Chennai", "country": "India", "lat": 12.99, "lon": 80.1693},
  MBJ: {"iata": "MBJ", "icao": "MKJS", "name": "Sangster International Airport", "city": "Montego Bay", "country": "Jamaica", "lat": 18.5034, "lon": -77.9132},
  MEL: {"iata": "MEL", "icao": "YMML", "name": "Melbourne Airport", "city": "Melbourne", "country": "Australia", "lat": -37.6707, "lon": 144.8379},
  MIA: {"iata": "MIA", "icao": "KMIA", "name": "Miami International Airport", "city": "Miami", "country": "United States", "lat": 25.796, "lon": -80.2898},
  MLE: {"iata": "MLE", "icao": "VRMM", "name": "Velana International Airport", "city": "Malé, Maldives", "country": "Maldives", "lat": 4.1918, "lon": 73.5291},
  MUC: {"iata": "MUC", "icao": "EDDM", "name": "Munich Airport", "city": "Munich", "country": "Germany", "lat": 48.3538, "lon": 11.7861},
  MVY: {"iata": "MVY", "icao": "KMVY", "name": "Martha's Vineyard Airport", "city": "Martha's Vineyard", "country": "United States", "lat": 41.3931, "lon": -70.6143},
  NAS: {"iata": "NAS", "icao": "MYNN", "name": "Lynden Pindling International Airport", "city": "Nassau", "country": "Bahamas", "lat": 25.039, "lon": -77.4662},
  NCE: {"iata": "NCE", "icao": "LFMN", "name": "Nice-Côte d'Azur Airport", "city": "Nice", "country": "France", "lat": 43.6584, "lon": 7.2159},
  OLB: {"iata": "OLB", "icao": "LIEO", "name": "Olbia Costa Smeralda Airport", "city": "Olbia, Sardinia", "country": "Italy", "lat": 40.899, "lon": 9.5185},
  PEK: {"iata": "PEK", "icao": "ZBAA", "name": "Beijing Capital International Airport", "city": "Beijing", "country": "China", "lat": 40.0773, "lon": 116.5967},
  PMI: {"iata": "PMI", "icao": "LEPA", "name": "Palma de Mallorca Airport", "city": "Palma de Mallorca", "country": "Spain", "lat": 39.5517, "lon": 2.7388},
  RUH: {"iata": "RUH", "icao": "OERK", "name": "King Khalid International Airport", "city": "Riyadh", "country": "Saudi Arabia", "lat": 24.9576, "lon": 46.6988},
  SBH: {"iata": "SBH", "icao": "TFFJ", "name": "St. Jean Airport", "city": "St Barths", "country": "Saint Barthélemy", "lat": 17.9044, "lon": -62.8433},
  SIN: {"iata": "SIN", "icao": "WSSS", "name": "Singapore Changi Airport", "city": "Singapore", "country": "Singapore", "lat": 1.3502, "lon": 103.994},
  SJD: {"iata": "SJD", "icao": "MMSD", "name": "Los Cabos International Airport", "city": "Los Cabos", "country": "Mexico", "lat": 23.1519, "lon": -109.7207},
  SUN: {"iata": "SUN", "icao": "KSUN", "name": "Friedman Memorial Airport", "city": "Sun Valley", "country": "United States", "lat": 43.5044, "lon": -114.296},
  SXM: {"iata": "SXM", "icao": "TNCM", "name": "Princess Juliana International Airport", "city": "St Maarten", "country": "Sint Maarten", "lat": 18.041, "lon": -63.1089},
  SXR: {"iata": "SXR", "icao": "VISR", "name": "Srinagar International Airport", "city": "Srinagar", "country": "India", "lat": 33.9871, "lon": 74.7742},
  SYD: {"iata": "SYD", "icao": "YSSY", "name": "Sydney Kingsford Smith International Airport", "city": "Sydney", "country": "Australia", "lat": -33.9461, "lon": 151.177},
  SZG: {"iata": "SZG", "icao": "LOWS", "name": "Salzburg Airport", "city": "Salzburg", "country": "Austria", "lat": 47.7933, "lon": 13.0043},
  TEB: {"iata": "TEB", "icao": "KTEB", "name": "Teterboro Airport", "city": "New York (Teterboro)", "country": "United States", "lat": 40.8501, "lon": -74.0608},
  TPE: {"iata": "TPE", "icao": "RCTP", "name": "Taiwan Taoyuan International Airport", "city": "Taipei", "country": "Taiwan", "lat": 25.0777, "lon": 121.233},
  UDR: {"iata": "UDR", "icao": "VAUD", "name": "Maharana Pratap Airport", "city": "Udaipur", "country": "India", "lat": 24.6177, "lon": 73.8961},
  VNY: {"iata": "VNY", "icao": "KVNY", "name": "Van Nuys Airport", "city": "Los Angeles (Van Nuys)", "country": "United States", "lat": 34.2098, "lon": -118.49},
  YVR: {"iata": "YVR", "icao": "CYVR", "name": "Vancouver International Airport", "city": "Vancouver", "country": "Canada", "lat": 49.1939, "lon": -123.184},
  YYC: {"iata": "YYC", "icao": "CYYC", "name": "Calgary International Airport", "city": "Calgary", "country": "Canada", "lat": 51.1188, "lon": -114.0099},
  YYZ: {"iata": "YYZ", "icao": "CYYZ", "name": "Toronto Pearson International Airport", "city": "Toronto", "country": "Canada", "lat": 43.6759, "lon": -79.6294},
  ZQN: {"iata": "ZQN", "icao": "NZQN", "name": "Queenstown Airport", "city": "Queenstown", "country": "New Zealand", "lat": -45.0192, "lon": 168.7464},
  ZRH: {"iata": "ZRH", "icao": "LSZH", "name": "Zürich Airport", "city": "Zurich", "country": "Switzerland", "lat": 47.4581, "lon": 8.5481},
};

export const JET_ROUTES: JetRoute[] = [
  { slug: "del-atq", from: "DEL", to: "ATQ", group: "india", distanceNm: 224 },
  { slug: "bom-atq", from: "BOM", to: "ATQ", group: "india", distanceNm: 765 },
  { slug: "del-ixc", from: "DEL", to: "IXC", group: "india", distanceNm: 128 },
  { slug: "bom-ixc", from: "BOM", to: "IXC", group: "india", distanceNm: 727 },
  { slug: "del-ixl", from: "DEL", to: "IXL", group: "india", distanceNm: 336 },
  { slug: "ixc-ixl", from: "IXC", to: "IXL", group: "india", distanceNm: 211 },
  { slug: "del-ixj", from: "DEL", to: "IXJ", group: "india", distanceNm: 274 },
  { slug: "del-sxr", from: "DEL", to: "SXR", group: "india", distanceNm: 347 },
  { slug: "del-aip", from: "DEL", to: "AIP", group: "india", distanceNm: 186 },
  { slug: "bom-aip", from: "BOM", to: "AIP", group: "india", distanceNm: 758 },
  { slug: "del-luh", from: "DEL", to: "LUH", group: "india", distanceNm: 150 },
  { slug: "del-bom", from: "DEL", to: "BOM", group: "india", distanceNm: 614 },
  { slug: "bom-gox", from: "BOM", to: "GOX", group: "india", distanceNm: 209 },
  { slug: "del-gox", from: "DEL", to: "GOX", group: "india", distanceNm: 790 },
  { slug: "blr-gox", from: "BLR", to: "GOX", group: "india", distanceNm: 271 },
  { slug: "bom-blr", from: "BOM", to: "BLR", group: "india", distanceNm: 450 },
  { slug: "bom-hyd", from: "BOM", to: "HYD", group: "india", distanceNm: 336 },
  { slug: "del-blr", from: "DEL", to: "BLR", group: "india", distanceNm: 923 },
  { slug: "del-maa", from: "DEL", to: "MAA", group: "india", distanceNm: 950 },
  { slug: "bom-maa", from: "BOM", to: "MAA", group: "india", distanceNm: 558 },
  { slug: "maa-blr", from: "MAA", to: "BLR", group: "india", distanceNm: 145 },
  { slug: "del-hyd", from: "DEL", to: "HYD", group: "india", distanceNm: 684 },
  { slug: "del-jai", from: "DEL", to: "JAI", group: "india", distanceNm: 124 },
  { slug: "del-udr", from: "DEL", to: "UDR", group: "india", distanceNm: 292 },
  { slug: "bom-udr", from: "BOM", to: "UDR", group: "india", distanceNm: 337 },
  { slug: "del-ded", from: "DEL", to: "DED", group: "india", distanceNm: 113 },
  { slug: "blr-cok", from: "BLR", to: "COK", group: "india", distanceNm: 198 },
  { slug: "atq-dxb", from: "ATQ", to: "DXB", group: "india", distanceNm: 1094 },
  { slug: "ixc-dxb", from: "IXC", to: "DXB", group: "india", distanceNm: 1179 },
  { slug: "del-ccu", from: "DEL", to: "CCU", group: "india", distanceNm: 709 },
  { slug: "bom-amd", from: "BOM", to: "AMD", group: "india", distanceNm: 240 },
  { slug: "bom-mle", from: "BOM", to: "MLE", group: "india", distanceNm: 895 },
  { slug: "teb-djt", from: "TEB", to: "DJT", group: "global", distanceNm: 902 },
  { slug: "teb-mia", from: "TEB", to: "MIA", group: "global", distanceNm: 956 },
  { slug: "teb-vny", from: "TEB", to: "VNY", group: "global", distanceNm: 2129 },
  { slug: "vny-las", from: "VNY", to: "LAS", group: "global", distanceNm: 199 },
  { slug: "vny-ase", from: "VNY", to: "ASE", group: "global", distanceNm: 634 },
  { slug: "teb-ase", from: "TEB", to: "ASE", group: "global", distanceNm: 1503 },
  { slug: "teb-ege", from: "TEB", to: "EGE", group: "global", distanceNm: 1499 },
  { slug: "teb-ack", from: "TEB", to: "ACK", group: "global", distanceNm: 183 },
  { slug: "teb-mvy", from: "TEB", to: "MVY", group: "global", distanceNm: 159 },
  { slug: "vny-sjd", from: "VNY", to: "SJD", group: "global", distanceNm: 808 },
  { slug: "mia-nas", from: "MIA", to: "NAS", group: "global", distanceNm: 160 },
  { slug: "vny-sun", from: "VNY", to: "SUN", group: "global", distanceNm: 591 },
  { slug: "teb-yyz", from: "TEB", to: "YYZ", group: "global", distanceNm: 300 },
  { slug: "mia-sbh", from: "MIA", to: "SBH", group: "global", distanceNm: 1080 },
  { slug: "mia-mbj", from: "MIA", to: "MBJ", group: "global", distanceNm: 457 },
  { slug: "teb-sxm", from: "TEB", to: "SXM", group: "global", distanceNm: 1481 },
  { slug: "dal-hou", from: "DAL", to: "HOU", group: "global", distanceNm: 208 },
  { slug: "yvr-yyc", from: "YVR", to: "YYC", group: "global", distanceNm: 371 },
  { slug: "ltn-nce", from: "LTN", to: "NCE", group: "global", distanceNm: 580 },
  { slug: "lbg-nce", from: "LBG", to: "NCE", group: "global", distanceNm: 375 },
  { slug: "fab-nce", from: "FAB", to: "NCE", group: "global", distanceNm: 560 },
  { slug: "ltn-ibz", from: "LTN", to: "IBZ", group: "global", distanceNm: 784 },
  { slug: "lbg-ltn", from: "LBG", to: "LTN", group: "global", distanceNm: 205 },
  { slug: "fab-gva", from: "FAB", to: "GVA", group: "global", distanceNm: 407 },
  { slug: "gva-olb", from: "GVA", to: "OLB", group: "global", distanceNm: 353 },
  { slug: "ltn-pmi", from: "LTN", to: "PMI", group: "global", distanceNm: 751 },
  { slug: "nce-olb", from: "NCE", to: "OLB", group: "global", distanceNm: 195 },
  { slug: "zrh-nce", from: "ZRH", to: "NCE", group: "global", distanceNm: 235 },
  { slug: "muc-olb", from: "MUC", to: "OLB", group: "global", distanceNm: 458 },
  { slug: "ltn-szg", from: "LTN", to: "SZG", group: "global", distanceNm: 572 },
  { slug: "ltn-zrh", from: "LTN", to: "ZRH", group: "global", distanceNm: 436 },
  { slug: "ltn-jmk", from: "LTN", to: "JMK", group: "global", distanceNm: 1387 },
  { slug: "ath-jmk", from: "ATH", to: "JMK", group: "global", distanceNm: 73 },
  { slug: "ltn-fao", from: "LTN", to: "FAO", group: "global", distanceNm: 949 },
  { slug: "lbg-gva", from: "LBG", to: "GVA", group: "global", distanceNm: 221 },
  { slug: "ltn-teb", from: "LTN", to: "TEB", group: "global", distanceNm: 2989 },
  { slug: "lbg-teb", from: "LBG", to: "TEB", group: "global", distanceNm: 3150 },
  { slug: "dwc-ltn", from: "DWC", to: "LTN", group: "global", distanceNm: 2978 },
  { slug: "dxb-ruh", from: "DXB", to: "RUH", group: "global", distanceNm: 472 },
  { slug: "dxb-bom", from: "DXB", to: "BOM", group: "global", distanceNm: 1040 },
  { slug: "dxb-del", from: "DXB", to: "DEL", group: "global", distanceNm: 1178 },
  { slug: "dxb-mle", from: "DXB", to: "MLE", group: "global", distanceNm: 1642 },
  { slug: "doh-ltn", from: "DOH", to: "LTN", group: "global", distanceNm: 2832 },
  { slug: "ruh-lbg", from: "RUH", to: "LBG", group: "global", distanceNm: 2514 },
  { slug: "jed-lbg", from: "JED", to: "LBG", group: "global", distanceNm: 2393 },
  { slug: "dxb-gva", from: "DXB", to: "GVA", group: "global", distanceNm: 2657 },
  { slug: "dxb-nce", from: "DXB", to: "NCE", group: "global", distanceNm: 2583 },
  { slug: "hkg-sin", from: "HKG", to: "SIN", group: "global", distanceNm: 1385 },
  { slug: "sin-dps", from: "SIN", to: "DPS", group: "global", distanceNm: 903 },
  { slug: "hkg-tpe", from: "HKG", to: "TPE", group: "global", distanceNm: 435 },
  { slug: "hkg-hnd", from: "HKG", to: "HND", group: "global", distanceNm: 1567 },
  { slug: "sin-bkk", from: "SIN", to: "BKK", group: "global", distanceNm: 765 },
  { slug: "del-mle", from: "DEL", to: "MLE", group: "global", distanceNm: 1477 },
  { slug: "syd-mel", from: "SYD", to: "MEL", group: "global", distanceNm: 381 },
  { slug: "syd-akl", from: "SYD", to: "AKL", group: "global", distanceNm: 1166 },
  { slug: "syd-zqn", from: "SYD", to: "ZQN", group: "global", distanceNm: 1047 },
  { slug: "jnb-cpt", from: "JNB", to: "CPT", group: "global", distanceNm: 687 },
  { slug: "gru-gig", from: "GRU", to: "GIG", group: "global", distanceNm: 182 },
  { slug: "hkg-pek", from: "HKG", to: "PEK", group: "global", distanceNm: 1075 },
  { slug: "sin-hnd", from: "SIN", to: "HND", group: "global", distanceNm: 2862 },
];
