// GENERATED FILE — do not edit by hand.
// Source: Crystal Cruises official voyage pages (permitted catalogue enrichment).
// Regenerate with: bun scripts/crystal-world-cruise-import.ts
// Imported 2026-09-11T06:42:21.541Z
import type { CrystalWorldCruiseRecord } from "./world-cruises";

export const CRYSTAL_WORLD_CRUISE_RECORDS: CrystalWorldCruiseRecord[] = [
  {
    year: 2027,
    code: "CSE-W139-270108",
    voyageId: 8416,
    title: "San Diego to Vancouver",
    description:
      "Pack your bags for the 2027 World Cruise, an enchanting voyage across the Pacific Ocean. Departing San Diego, we set our course due south to explore the western reaches of Central and South America before the azure waters of the Pacific lure us out to embrace the pure shores of the South Sea Islands. Restless for adventure, we head to New Zealand and Australia, then meander through sultry Indonesia to our westernmost point, Singapore and Thailand. We curve around to examine three pearls of the east, China, South Korea and Japan, before crossing continents once more to the awesome wilds of Alaska and our final port, the mighty Canadian city of Vancouver. Embark on this transformative experience enveloped in the warm hospitality and companionship of our Crystal family.",
    ship: "Crystal Serenity",
    shipCode: "CSE",
    nights: 139,
    embarkDate: "2027-01-08",
    debarkDate: "2027-05-27",
    embarkPort: "San Diego",
    debarkPort: "Vancouver",
    countries: 28,
    priceFrom: 76200,
    currency: "USD",
    media: {
      hero: "https://stcontentprodeastus001.blob.core.windows.net/ecm/EasterIsland-f7521a91-b283-4973-a71c-7171cafc8ecd.jpg",
      gallery: [
        "https://stcontentprodeastus001.blob.core.windows.net/ecm/easterland_squared-9003298f-395a-4a7c-a924-051b95d26ac3.png",
      ],
      mapSvg: "https://stcontentprodeastus001.blob.core.windows.net/ecm/maps/Images/226396.svg",
      mapPng: "https://stcontentprodeastus001.blob.core.windows.net/ecm/maps/Images/226397.png",
      itineraryPdf: "[object Object]",
    },
    sourceUrl: "https://www.crystalcruises.com/cruises/none-cse-w139-270108",
    itinerary: [
      {
        day: 1,
        date: "2027-01-08",
        port: "San Diego",
        portCode: "SAN",
        country: "United States of America",
        dressCode: "Evening Resort",
      },
      {
        day: 2,
        date: "2027-01-09",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 3,
        date: "2027-01-10",
        port: "Cabo San Lucas (Bahia California Sur)",
        portCode: "CSL",
        country: "Mexico",
        arrive: "13:00",
        depart: "21:00",
        dressCode: "Evening Resort",
      },
      {
        day: 4,
        date: "2027-01-11",
        port: "Mazatlan",
        portCode: "MZT",
        country: "Mexico",
        arrive: "10:00",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 5,
        date: "2027-01-12",
        port: "Puerto Vallarta",
        portCode: "PVR",
        country: "Mexico",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 6,
        date: "2027-01-13",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 7,
        date: "2027-01-14",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 8,
        date: "2027-01-15",
        port: "Acajutla",
        portCode: "AQJ",
        country: "El Salvador",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 9,
        date: "2027-01-16",
        port: "Playa Flamingo",
        portCode: "FMG",
        country: "Costa Rica",
        arrive: "11:00",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 10,
        date: "2027-01-17",
        port: "Puntarenas",
        portCode: "PAS",
        country: "Costa Rica",
        arrive: "09:30",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 11,
        date: "2027-01-18",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 12,
        date: "2027-01-19",
        port: "Manta",
        portCode: "MEC",
        country: "Ecuador",
        arrive: "10:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 13,
        date: "2027-01-20",
        port: "Guayaquil",
        portCode: "GYE",
        country: "Ecuador",
        arrive: "08:00",
        depart: "23:00",
        dressCode: "Evening Resort",
      },
      {
        day: 14,
        date: "2027-01-21",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 15,
        date: "2027-01-22",
        port: "Salaverry",
        portCode: "SVY",
        country: "Peru",
        arrive: "07:00",
        depart: "16:00",
        dressCode: "Evening Resort",
      },
      {
        day: 16,
        date: "2027-01-23",
        port: "Callao (Lima)",
        portCode: "CLL",
        country: "Peru",
        arrive: "08:00",
        dressCode: "Evening Resort",
      },
      {
        day: 17,
        date: "2027-01-24",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 18,
        date: "2027-01-25",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 19,
        date: "2027-01-26",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 20,
        date: "2027-01-27",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 21,
        date: "2027-01-28",
        port: "Hanga Roa (Easter Island)",
        portCode: "IPC",
        country: "Chile",
        arrive: "12:00",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 22,
        date: "2027-01-29",
        port: "Hanga Roa (Easter Island)",
        portCode: "IPC",
        country: "Chile",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 23,
        date: "2027-01-30",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 24,
        date: "2027-01-31",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 25,
        date: "2027-02-01",
        port: "Adamstown",
        portCode: "PCN",
        country: "Pitcairn Island",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 26,
        date: "2027-02-02",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 27,
        date: "2027-02-03",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 28,
        date: "2027-02-04",
        port: "Rangiroa",
        portCode: "RGI",
        country: "French Polynesia",
        arrive: "09:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 29,
        date: "2027-02-05",
        port: "Fakarava",
        portCode: "FAV",
        country: "French Polynesia",
        arrive: "07:00",
        depart: "14:00",
        dressCode: "Resort Casual",
      },
      {
        day: 30,
        date: "2027-02-06",
        port: "Huahine",
        portCode: "HUH",
        country: "French Polynesia",
        arrive: "09:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 31,
        date: "2027-02-07",
        port: "Papeete (Tahiti)",
        portCode: "PPT",
        country: "French Polynesia",
        arrive: "08:00",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 32,
        date: "2027-02-08",
        port: "Papeete (Tahiti)",
        portCode: "PPT",
        country: "French Polynesia",
        dressCode: "Evening Resort",
      },
      {
        day: 33,
        date: "2027-02-09",
        port: "Moorea Island",
        portCode: "MOZ",
        country: "French Polynesia",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 34,
        date: "2027-02-10",
        port: "Raiatea",
        portCode: "RFP",
        country: "French Polynesia",
        arrive: "08:00",
        depart: "23:00",
        dressCode: "Evening Resort",
      },
      {
        day: 35,
        date: "2027-02-11",
        port: "Bora Bora",
        portCode: "BOB",
        country: "French Polynesia",
        arrive: "08:00",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 36,
        date: "2027-02-12",
        port: "Bora Bora",
        portCode: "BOB",
        country: "French Polynesia",
        depart: "16:00",
        dressCode: "Evening Resort",
      },
      {
        day: 37,
        date: "2027-02-13",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 38,
        date: "2027-02-14",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 39,
        date: "2027-02-15",
        port: "Pago Pago",
        portCode: "PPG",
        country: "American samoa",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 40,
        date: "2027-02-17",
        port: "International Date Line - Lose a Day",
        portCode: "C00",
        dressCode: "Evening Resort",
      },
      {
        day: 40,
        date: "2027-02-17",
        port: "Apia",
        portCode: "APW",
        country: "Samoa Islands",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 41,
        date: "2027-02-18",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 42,
        date: "2027-02-19",
        port: "Suva",
        portCode: "SUV",
        country: "Fiji",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 43,
        date: "2027-02-20",
        port: "Lautoka",
        portCode: "LTK",
        country: "Fiji",
        arrive: "07:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 44,
        date: "2027-02-21",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 45,
        date: "2027-02-22",
        port: "Champagne Bay",
        portCode: "CPG",
        country: "Vanuatu",
        arrive: "08:00",
        depart: "16:00",
        dressCode: "Evening Resort",
      },
      {
        day: 46,
        date: "2027-02-23",
        port: "Port Vila",
        portCode: "VLI",
        country: "Vanuatu",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 47,
        date: "2027-02-24",
        port: "Mystery Island, Anelghowhat",
        portCode: "MYS",
        country: "Vanuatu",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 48,
        date: "2027-02-25",
        port: "Lifou",
        portCode: "LIF",
        country: "New Caledonia",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 49,
        date: "2027-02-26",
        port: "Noumea",
        portCode: "NOU",
        country: "New Caledonia",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 50,
        date: "2027-02-27",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 51,
        date: "2027-02-28",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 52,
        date: "2027-03-01",
        port: "Bay of Islands",
        portCode: "BAY",
        country: "New Zealand",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 53,
        date: "2027-03-02",
        port: "Auckland",
        portCode: "AKL",
        country: "New Zealand",
        arrive: "07:00",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 54,
        date: "2027-03-03",
        port: "Auckland",
        portCode: "AKL",
        country: "New Zealand",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 55,
        date: "2027-03-04",
        port: "Tauranga",
        portCode: "TRG",
        country: "New Zealand",
        arrive: "07:00",
        depart: "16:00",
        dressCode: "Evening Resort",
      },
      {
        day: 56,
        date: "2027-03-05",
        port: "Napier",
        portCode: "NPE",
        country: "New Zealand",
        arrive: "10:00",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 57,
        date: "2027-03-06",
        port: "Wellington",
        portCode: "WLG",
        country: "New Zealand",
        arrive: "09:00",
        depart: "20:00",
        dressCode: "Evening Resort",
      },
      {
        day: 58,
        date: "2027-03-07",
        port: "Lyttelton (Christchurch)",
        portCode: "LYT",
        country: "New Zealand",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 59,
        date: "2027-03-08",
        port: "Port Chalmers (Dunedin)",
        portCode: "POE",
        country: "New Zealand",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 60,
        date: "2027-03-09",
        port: "Cruising Dusky Sound",
        portCode: "DKS",
        country: "New Zealand",
        dressCode: "Evening Resort",
      },
      {
        day: 60,
        date: "2027-03-09",
        port: "Cruising Doubtful Sound",
        portCode: "C98",
        country: "New Zealand",
        dressCode: "Evening Resort",
      },
      {
        day: 60,
        date: "2027-03-09",
        port: "Cruising Milford Sound",
        portCode: "MFN",
        country: "New Zealand",
        dressCode: "Evening Resort",
      },
      {
        day: 61,
        date: "2027-03-10",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 62,
        date: "2027-03-11",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 63,
        date: "2027-03-12",
        port: "Melbourne",
        portCode: "MEL",
        country: "Australia",
        arrive: "10:00",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 64,
        date: "2027-03-13",
        port: "Melbourne",
        portCode: "MEL",
        country: "Australia",
        depart: "20:00",
        dressCode: "Evening Resort",
      },
      {
        day: 65,
        date: "2027-03-14",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 66,
        date: "2027-03-15",
        port: "Sydney",
        portCode: "SYD",
        country: "Australia",
        arrive: "08:00",
        depart: "23:00",
        dressCode: "Evening Resort",
      },
      {
        day: 67,
        date: "2027-03-16",
        port: "Newcastle",
        portCode: "NTL",
        country: "Australia",
        arrive: "08:00",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 68,
        date: "2027-03-17",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 69,
        date: "2027-03-18",
        port: "Brisbane",
        portCode: "BNE",
        country: "Australia",
        arrive: "07:00",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 70,
        date: "2027-03-19",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 71,
        date: "2027-03-20",
        port: "Airlie Beach",
        portCode: "WSY",
        country: "Australia",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 72,
        date: "2027-03-21",
        port: "Cairns",
        portCode: "CNS",
        country: "Australia",
        arrive: "10:00",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 73,
        date: "2027-03-22",
        port: "Cairns",
        portCode: "CNS",
        country: "Australia",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 74,
        date: "2027-03-23",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 75,
        date: "2027-03-24",
        port: "Alotau",
        portCode: "GUR",
        country: "Papua New Guinea",
        arrive: "07:00",
        depart: "16:00",
        dressCode: "Evening Resort",
      },
      {
        day: 76,
        date: "2027-03-25",
        port: "Port Moresby",
        portCode: "POM",
        country: "Papua New Guinea",
        arrive: "10:00",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 77,
        date: "2027-03-26",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 78,
        date: "2027-03-27",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 79,
        date: "2027-03-28",
        port: "Darwin",
        portCode: "DRW",
        country: "Australia",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 80,
        date: "2027-03-29",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 81,
        date: "2027-03-30",
        port: "Komodo Island",
        portCode: "KMD",
        country: "Indonesia",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 82,
        date: "2027-03-31",
        port: "Benoa (Bali)",
        portCode: "BOA",
        country: "Indonesia",
        arrive: "12:00",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 83,
        date: "2027-04-01",
        port: "Benoa (Bali)",
        portCode: "BOA",
        country: "Indonesia",
        depart: "21:00",
        dressCode: "Evening Resort",
      },
      {
        day: 84,
        date: "2027-04-02",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 85,
        date: "2027-04-03",
        port: "Semarang (Gateway for Borobodur)",
        portCode: "SRG",
        country: "Indonesia",
        arrive: "07:00",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 86,
        date: "2027-04-04",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 87,
        date: "2027-04-05",
        port: "Singapore",
        portCode: "SIN",
        country: "Singapore",
        arrive: "12:00",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 88,
        date: "2027-04-06",
        port: "Singapore",
        portCode: "SIN",
        country: "Singapore",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 89,
        date: "2027-04-07",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 90,
        date: "2027-04-08",
        port: "Koh Samui",
        portCode: "USM",
        country: "Thailand",
        arrive: "09:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 91,
        date: "2027-04-09",
        port: "Laem chabang (Bangkok)",
        portCode: "LCH",
        country: "Thailand",
        arrive: "08:00",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 92,
        date: "2027-04-10",
        port: "Laem chabang (Bangkok)",
        portCode: "LCH",
        country: "Thailand",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 93,
        date: "2027-04-11",
        port: "Ko Kut",
        portCode: "KUT",
        country: "Thailand",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 94,
        date: "2027-04-12",
        port: "Phu Quoc",
        portCode: "PQC",
        country: "Vietnam",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 95,
        date: "2027-04-13",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 96,
        date: "2027-04-14",
        port: "Ho Chi Minh City",
        portCode: "SGN",
        country: "Vietnam",
        arrive: "08:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 97,
        date: "2027-04-15",
        port: "Ho Chi Minh City",
        portCode: "SGN",
        country: "Vietnam",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 98,
        date: "2027-04-16",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 99,
        date: "2027-04-17",
        port: "Muara",
        portCode: "MUA",
        country: "Brunei",
        arrive: "08:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 100,
        date: "2027-04-18",
        port: "Kota Kinabalu",
        portCode: "BKI",
        country: "Malaysia",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 101,
        date: "2027-04-19",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 102,
        date: "2027-04-20",
        port: "Boracay",
        portCode: "BOR",
        country: "Philippines",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 103,
        date: "2027-04-21",
        port: "Manila",
        portCode: "MNL",
        country: "Philippines",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 104,
        date: "2027-04-22",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 105,
        date: "2027-04-23",
        port: "Hong Kong",
        portCode: "HKG",
        country: "China",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 106,
        date: "2027-04-24",
        port: "Hong Kong",
        portCode: "HKG",
        country: "China",
        depart: "14:00",
        dressCode: "Evening Resort",
      },
      {
        day: 107,
        date: "2027-04-25",
        port: "Xiamen",
        portCode: "XMN",
        country: "China",
        arrive: "10:00",
        depart: "20:00",
        dressCode: "Evening Resort",
      },
      {
        day: 108,
        date: "2027-04-26",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 109,
        date: "2027-04-27",
        port: "Shanghai",
        portCode: "SGH",
        country: "China",
        arrive: "11:00",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 110,
        date: "2027-04-28",
        port: "Shanghai",
        portCode: "SGH",
        country: "China",
        overnight: true,
        dressCode: "Evening Resort",
      },
      {
        day: 111,
        date: "2027-04-29",
        port: "Shanghai",
        portCode: "SGH",
        country: "China",
        depart: "16:00",
        dressCode: "Evening Resort",
      },
      {
        day: 112,
        date: "2027-04-30",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 113,
        date: "2027-05-01",
        port: "Busan",
        portCode: "PUS",
        country: "South Korea",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 114,
        date: "2027-05-02",
        port: "Hiroshima",
        portCode: "HIJ",
        country: "Japan",
        arrive: "10:00",
        depart: "20:00",
        dressCode: "Evening Resort",
      },
      {
        day: 115,
        date: "2027-05-03",
        port: "Beppu (Kyushu Island)",
        portCode: "BPU",
        country: "Japan",
        arrive: "08:30",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 116,
        date: "2027-05-04",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 117,
        date: "2027-05-05",
        port: "Wakayama",
        portCode: "WAK",
        country: "Japan",
        arrive: "07:00",
        depart: "20:00",
        dressCode: "Evening Resort",
      },
      {
        day: 118,
        date: "2027-05-06",
        port: "Nagoya",
        portCode: "NGO",
        country: "Japan",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 119,
        date: "2027-05-07",
        port: "Yokohama (Tokyo)",
        portCode: "YOK",
        country: "Japan",
        arrive: "07:30",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 120,
        date: "2027-05-08",
        port: "Yokohama (Tokyo)",
        portCode: "YOK",
        country: "Japan",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 121,
        date: "2027-05-09",
        port: "Hitachinaka",
        portCode: "HIC",
        country: "Japan",
        arrive: "09:00",
        depart: "19:00",
        dressCode: "Evening Resort",
      },
      {
        day: 122,
        date: "2027-05-10",
        port: "Sendai",
        portCode: "SDJ",
        country: "Japan",
        arrive: "07:00",
        depart: "16:00",
        dressCode: "Evening Resort",
      },
      {
        day: 123,
        date: "2027-05-11",
        port: "Hakodate (Hokkaido)",
        portCode: "HKD",
        country: "Japan",
        arrive: "10:00",
        depart: "21:00",
        dressCode: "Evening Resort",
      },
      {
        day: 124,
        date: "2027-05-12",
        port: "Aomori",
        portCode: "AOJ",
        country: "Japan",
        arrive: "07:00",
        depart: "16:00",
        dressCode: "Evening Resort",
      },
      {
        day: 125,
        date: "2027-05-13",
        port: "Kushiro",
        portCode: "KUH",
        country: "Japan",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 126,
        date: "2027-05-14",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 127,
        date: "2027-05-15",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 128,
        date: "2027-05-15",
        port: "International Date Line - Gain a Day",
        portCode: "C15",
        dressCode: "Evening Resort",
      },
      {
        day: 129,
        date: "2027-05-16",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 130,
        date: "2027-05-17",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Formal Evening",
      },
      {
        day: 131,
        date: "2027-05-18",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Evening Resort",
      },
      {
        day: 132,
        date: "2027-05-19",
        port: "Kodiak Island",
        portCode: "ADQ",
        country: "United States of America",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Evening Resort",
      },
      {
        day: 133,
        date: "2027-05-20",
        port: "Seward (Anchorage)",
        portCode: "SWD",
        country: "United States of America",
        arrive: "07:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 134,
        date: "2027-05-21",
        port: "Cruising Hubbard Glacier",
        portCode: "E76",
        country: "United States of America",
        dressCode: "Evening Resort",
      },
      {
        day: 135,
        date: "2027-05-22",
        port: "Skagway",
        portCode: "SGY",
        country: "United States of America",
        arrive: "09:00",
        depart: "20:00",
        dressCode: "Evening Resort",
      },
      {
        day: 136,
        date: "2027-05-23",
        port: "Icy Strait Point",
        portCode: "ISP",
        country: "United States of America",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 137,
        date: "2027-05-24",
        port: "Sitka",
        portCode: "SIT",
        country: "United States of America",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Evening Resort",
      },
      {
        day: 138,
        date: "2027-05-25",
        port: "Wrangell",
        portCode: "WRG",
        country: "United States of America",
        arrive: "07:00",
        depart: "16:00",
        dressCode: "Evening Resort",
      },
      {
        day: 139,
        date: "2027-05-26",
        port: "Cruising Seymour Narrows",
        portCode: "R02",
        country: "Canada",
        dressCode: "Evening Resort",
      },
      {
        day: 140,
        date: "2027-05-27",
        port: "Vancouver",
        portCode: "VAN",
        country: "Canada",
        arrive: "06:00",
        dressCode: "Evening Resort",
      },
    ],
    suites: [
      {
        category: "CRYSTAL PENTHOUSE SUITE",
        categoryCode: "ow",
        priceDouble: 274500,
        priceSingle: 521500,
        priceChild: 53500,
        portCharge: 8500,
        maxCapacity: 4,
        availability: 0,
      },
      {
        category: "SAPPHIRE VERANDA SUITE",
        categoryCode: "gx",
        priceDouble: 114800,
        priceSingle: 172200,
        priceChild: 49400,
        portCharge: 8500,
        maxCapacity: 4,
        availability: 0,
      },
      {
        category: "JUNIOR CRYSTAL PENTHOUSE SUITE",
        categoryCode: "ro",
        priceDouble: 186500,
        priceSingle: 353500,
        priceChild: 49000,
        portCharge: 8500,
        maxCapacity: 4,
        availability: 0,
      },
      {
        category: "AQUAMARINE VERANDA SUITE",
        categoryCode: "ve",
        priceDouble: 89100,
        priceSingle: 133600,
        priceChild: 48100,
        portCharge: 8500,
        maxCapacity: 4,
        availability: 0,
      },
      {
        category: "DOUBLE GUEST ROOM WITH OCEAN VIEW",
        categoryCode: "ov",
        priceDouble: 67700,
        priceSingle: 117800,
        priceChild: 39900,
        portCharge: 8500,
        maxCapacity: 2,
        availability: 0,
      },
      {
        category: "SINGLE GUEST ROOM WITH OCEAN VIEW",
        categoryCode: "os",
        priceDouble: 106100,
        priceSingle: 106100,
        portCharge: 8500,
        maxCapacity: 4,
        availability: 0,
      },
      {
        category: "DOUBLE GUEST ROOM WITH VERANDA",
        categoryCode: "oc",
        priceDouble: 77500,
        priceSingle: 127100,
        priceChild: 45000,
        portCharge: 8500,
        maxCapacity: 4,
        availability: 0,
      },
    ],
  },
  {
    year: 2028,
    code: "CSY-W150-280111",
    voyageId: 8483,
    title: "Roundtrip Fort Lauderdale",
    ship: "Crystal Symphony",
    shipCode: "CSY",
    nights: 150,
    embarkDate: "2028-01-11",
    debarkDate: "2028-06-10",
    embarkPort: "Fort Lauderdale",
    debarkPort: "Fort Lauderdale",
    countries: 39,
    priceFrom: 72500,
    currency: "USD",
    media: {
      hero: "https://stcontentprodeastus001.blob.core.windows.net/ecm/CSY-W150-280111 AdobeStock_265064644-landscape-e1fa419b-e9d1-40da-80ef-e6cbfa8ee30a.jpg",
      gallery: [
        "https://stcontentprodeastus001.blob.core.windows.net/ecm/CSY-W150-280111 AdobeStock_265064644-square-81707c1e-73e6-4407-b3f1-cc9ea9d29e21.jpg",
      ],
      mapSvg: "https://stcontentprodeastus001.blob.core.windows.net/ecm/maps/Images/226376.svg",
      mapPng: "https://stcontentprodeastus001.blob.core.windows.net/ecm/maps/Images/226377.png",
      itineraryPdf: "[object Object]",
    },
    sourceUrl: "https://www.crystalcruises.com/cruises/none-csy-w150-280111",
    itinerary: [
      {
        day: 1,
        date: "2028-01-11",
        port: "Fort Lauderdale",
        portCode: "FLL",
        country: "United States of America",
        depart: "21:00",
        dressCode: "Evening Resort",
      },
      {
        day: 2,
        date: "2028-01-12",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 3,
        date: "2028-01-13",
        port: "Cozumel",
        portCode: "CZM",
        country: "Mexico",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 4,
        date: "2028-01-14",
        port: "Belize City",
        portCode: "BZE",
        country: "Belize",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 5,
        date: "2028-01-15",
        port: "Santo Tomas",
        portCode: "STC",
        country: "Guatemala",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 6,
        date: "2028-01-16",
        port: "Roatan Island",
        portCode: "RTB",
        country: "Honduras",
        arrive: "07:00",
        depart: "15:00",
        dressCode: "Resort Casual",
      },
      {
        day: 7,
        date: "2028-01-17",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 8,
        date: "2028-01-18",
        port: "Puerto Limón",
        portCode: "LIO",
        country: "Costa Rica",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 9,
        date: "2028-01-19",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 10,
        date: "2028-01-20",
        port: "Cartagena",
        portCode: "CTG",
        country: "Colombia",
        arrive: "07:00",
        depart: "14:30",
        dressCode: "Resort Casual",
      },
      {
        day: 11,
        date: "2028-01-21",
        port: "Panama Canal Transit",
        portCode: "C81",
        country: "Panama",
        dressCode: "Resort Casual",
      },
      {
        day: 11,
        date: "2028-01-21",
        port: "Fuerte Amador (Panama City)",
        portCode: "PTY",
        country: "Panama",
        arrive: "21:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 12,
        date: "2028-01-22",
        port: "Fuerte Amador (Panama City)",
        portCode: "PTY",
        country: "Panama",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 13,
        date: "2028-01-23",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 14,
        date: "2028-01-24",
        port: "Manta",
        portCode: "MEC",
        country: "Ecuador",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 15,
        date: "2028-01-25",
        port: "Guayaquil",
        portCode: "GYE",
        country: "Ecuador",
        arrive: "09:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 16,
        date: "2028-01-26",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 17,
        date: "2028-01-27",
        port: "Salaverry",
        portCode: "SVY",
        country: "Peru",
        arrive: "07:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 18,
        date: "2028-01-28",
        port: "Callao (Lima)",
        portCode: "CLL",
        country: "Peru",
        arrive: "09:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 19,
        date: "2028-01-29",
        port: "Callao (Lima)",
        portCode: "CLL",
        country: "Peru",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 20,
        date: "2028-01-30",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 21,
        date: "2028-01-31",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 22,
        date: "2028-02-01",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 23,
        date: "2028-02-02",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 24,
        date: "2028-02-03",
        port: "Hanga Roa (Easter Island)",
        portCode: "IPC",
        country: "Chile",
        arrive: "12:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 25,
        date: "2028-02-04",
        port: "Hanga Roa (Easter Island)",
        portCode: "IPC",
        country: "Chile",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 26,
        date: "2028-02-05",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 27,
        date: "2028-02-06",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 28,
        date: "2028-02-07",
        port: "Adamstown",
        portCode: "PCN",
        country: "Pitcairn Island",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 29,
        date: "2028-02-08",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 30,
        date: "2028-02-09",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 31,
        date: "2028-02-10",
        port: "Fakarava",
        portCode: "FAV",
        country: "French Polynesia",
        arrive: "09:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 32,
        date: "2028-02-11",
        port: "Rangiroa",
        portCode: "RGI",
        country: "French Polynesia",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 33,
        date: "2028-02-12",
        port: "Huahine",
        portCode: "HUH",
        country: "French Polynesia",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 34,
        date: "2028-02-13",
        port: "Papeete (Tahiti)",
        portCode: "PPT",
        country: "French Polynesia",
        arrive: "06:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 35,
        date: "2028-02-14",
        port: "Papeete (Tahiti)",
        portCode: "PPT",
        country: "French Polynesia",
        depart: "06:00",
        dressCode: "Resort Casual",
      },
      {
        day: 35,
        date: "2028-02-14",
        port: "Moorea Island",
        portCode: "MOZ",
        country: "French Polynesia",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 36,
        date: "2028-02-15",
        port: "Raiatea",
        portCode: "RFP",
        country: "French Polynesia",
        arrive: "07:00",
        depart: "20:00",
        dressCode: "Resort Casual",
      },
      {
        day: 37,
        date: "2028-02-16",
        port: "Bora Bora",
        portCode: "BOB",
        country: "French Polynesia",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 38,
        date: "2028-02-17",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 39,
        date: "2028-02-18",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 40,
        date: "2028-02-19",
        port: "Pago Pago",
        portCode: "PPG",
        country: "American samoa",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 41,
        date: "2028-02-20",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 41,
        date: "2028-02-20",
        port: "International Date Line - Lose a Day",
        portCode: "C00",
        dressCode: "Resort Casual",
      },
      {
        day: 42,
        date: "2028-02-22",
        port: "Suva",
        portCode: "SUV",
        country: "Fiji",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 43,
        date: "2028-02-23",
        port: "Lautoka",
        portCode: "LTK",
        country: "Fiji",
        arrive: "07:00",
        depart: "20:00",
        dressCode: "Resort Casual",
      },
      {
        day: 44,
        date: "2028-02-24",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 45,
        date: "2028-02-25",
        port: "Mystery Island, Anelghowhat",
        portCode: "MYS",
        country: "Vanuatu",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 46,
        date: "2028-02-26",
        port: "Lifou",
        portCode: "LIF",
        country: "New Caledonia",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 47,
        date: "2028-02-27",
        port: "Noumea",
        portCode: "NOU",
        country: "New Caledonia",
        arrive: "08:00",
        depart: "21:00",
        dressCode: "Resort Casual",
      },
      {
        day: 48,
        date: "2028-02-28",
        port: "Isle of Pines",
        portCode: "ILP",
        country: "New Caledonia",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 49,
        date: "2028-02-29",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 50,
        date: "2028-03-01",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 51,
        date: "2028-03-02",
        port: "Bay of Islands",
        portCode: "BAY",
        country: "New Zealand",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 52,
        date: "2028-03-03",
        port: "Auckland",
        portCode: "AKL",
        country: "New Zealand",
        arrive: "07:00",
        depart: "23:00",
        dressCode: "Resort Casual",
      },
      {
        day: 53,
        date: "2028-03-04",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 54,
        date: "2028-03-05",
        port: "Napier",
        portCode: "NPE",
        country: "New Zealand",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 55,
        date: "2028-03-06",
        port: "Wellington",
        portCode: "WLG",
        country: "New Zealand",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 56,
        date: "2028-03-07",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 57,
        date: "2028-03-08",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 58,
        date: "2028-03-09",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 59,
        date: "2028-03-10",
        port: "Melbourne",
        portCode: "MEL",
        country: "Australia",
        arrive: "07:00",
        dressCode: "Resort Casual",
      },
      {
        day: 60,
        date: "2028-03-11",
        port: "Portland",
        portCode: "PTJ",
        country: "Australia",
        arrive: "09:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 61,
        date: "2028-03-12",
        port: "Adelaide",
        portCode: "ADL",
        country: "Australia",
        arrive: "12:00",
        depart: "23:00",
        dressCode: "Resort Casual",
      },
      {
        day: 62,
        date: "2028-03-13",
        port: "Kangaroo Island",
        portCode: "KAG",
        country: "Australia",
        arrive: "08:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 63,
        date: "2028-03-14",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 64,
        date: "2028-03-15",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 65,
        date: "2028-03-16",
        port: "Albany",
        portCode: "ALH",
        country: "Australia",
        arrive: "07:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 66,
        date: "2028-03-17",
        port: "Fremantle (Perth)",
        portCode: "FRE",
        country: "Australia",
        arrive: "14:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 67,
        date: "2028-03-18",
        port: "Fremantle (Perth)",
        portCode: "FRE",
        country: "Australia",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 68,
        date: "2028-03-19",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 69,
        date: "2028-03-20",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 70,
        date: "2028-03-21",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 71,
        date: "2028-03-22",
        port: "Benoa (Bali)",
        portCode: "BOA",
        country: "Indonesia",
        arrive: "08:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 72,
        date: "2028-03-23",
        port: "Benoa (Bali)",
        portCode: "BOA",
        country: "Indonesia",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 73,
        date: "2028-03-24",
        port: "Celukan Bawang (Bali)",
        portCode: "CEL",
        country: "Indonesia",
        arrive: "07:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 74,
        date: "2028-03-25",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 75,
        date: "2028-03-26",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 76,
        date: "2028-03-27",
        port: "Puerto Princesa",
        portCode: "PPS",
        country: "Philippines",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 77,
        date: "2028-03-28",
        port: "Boracay",
        portCode: "BOR",
        country: "Philippines",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 78,
        date: "2028-03-29",
        port: "Manila",
        portCode: "MNL",
        country: "Philippines",
        arrive: "08:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 79,
        date: "2028-03-30",
        port: "Manila",
        portCode: "MNL",
        country: "Philippines",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 80,
        date: "2028-03-31",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 81,
        date: "2028-04-01",
        port: "Nha Trang",
        portCode: "NHA",
        country: "Vietnam",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 82,
        date: "2028-04-02",
        port: "Ho Chi Minh City",
        portCode: "SGN",
        country: "Vietnam",
        arrive: "12:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 83,
        date: "2028-04-03",
        port: "Ho Chi Minh City",
        portCode: "SGN",
        country: "Vietnam",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 84,
        date: "2028-04-04",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 85,
        date: "2028-04-05",
        port: "Singapore",
        portCode: "SIN",
        country: "Singapore",
        arrive: "10:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 86,
        date: "2028-04-06",
        port: "Singapore",
        portCode: "SIN",
        country: "Singapore",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 87,
        date: "2028-04-07",
        port: "Port Klang (Kuala Lumpur)",
        portCode: "PKG",
        country: "Malaysia",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 88,
        date: "2028-04-08",
        port: "Penang",
        portCode: "PEN",
        country: "Malaysia",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 89,
        date: "2028-04-09",
        port: "Phuket",
        portCode: "HKT",
        country: "Thailand",
        arrive: "09:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 90,
        date: "2028-04-10",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 91,
        date: "2028-04-11",
        port: "Port Blair/Sri Vuaya Puram",
        portCode: "IXZ",
        country: "India",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 92,
        date: "2028-04-12",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 93,
        date: "2028-04-13",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 94,
        date: "2028-04-14",
        port: "Hambantota",
        portCode: "HBA",
        country: "Sri Lanka",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 95,
        date: "2028-04-15",
        port: "Colombo",
        portCode: "CMB",
        country: "Sri Lanka",
        arrive: "08:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 96,
        date: "2028-04-16",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 97,
        date: "2028-04-17",
        port: "Kochi (India)",
        portCode: "COK",
        country: "India",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 98,
        date: "2028-04-18",
        port: "New Mangalore",
        portCode: "MAI",
        country: "India",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 99,
        date: "2028-04-19",
        port: "Mormugao (Goa)",
        portCode: "MRM",
        country: "India",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 100,
        date: "2028-04-20",
        port: "Mumbai",
        portCode: "BOM",
        country: "India",
        arrive: "09:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 101,
        date: "2028-04-21",
        port: "Mumbai",
        portCode: "BOM",
        country: "India",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 102,
        date: "2028-04-22",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 103,
        date: "2028-04-23",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 104,
        date: "2028-04-24",
        port: "Musandam Peninsula",
        portCode: "KHS",
        country: "Oman",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 105,
        date: "2028-04-25",
        port: "Abu Dhabi",
        portCode: "AUH",
        country: "United Arab Emirates",
        arrive: "08:00",
        depart: "22:00",
        dressCode: "Resort Casual",
      },
      {
        day: 106,
        date: "2028-04-26",
        port: "Dubai",
        portCode: "DXB",
        country: "United Arab Emirates",
        arrive: "07:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 107,
        date: "2028-04-27",
        port: "Dubai",
        portCode: "DXB",
        country: "United Arab Emirates",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 108,
        date: "2028-04-28",
        port: "Fujairah",
        portCode: "FJR",
        country: "United Arab Emirates",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 109,
        date: "2028-04-29",
        port: "Muscat",
        portCode: "MCT",
        country: "Oman",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 110,
        date: "2028-04-30",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 111,
        date: "2028-05-01",
        port: "Salalah",
        portCode: "SLL",
        country: "Oman",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 112,
        date: "2028-05-02",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 113,
        date: "2028-05-03",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 114,
        date: "2028-05-04",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 115,
        date: "2028-05-05",
        port: "Jeddah",
        portCode: "JED",
        country: "Saudi Arabia",
        arrive: "06:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 116,
        date: "2028-05-06",
        port: "Jeddah",
        portCode: "JED",
        country: "Saudi Arabia",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 117,
        date: "2028-05-07",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 118,
        date: "2028-05-08",
        port: "Aqaba (Petra)",
        portCode: "AQJ",
        country: "Jordan",
        arrive: "07:00",
        depart: "21:00",
        dressCode: "Resort Casual",
      },
      {
        day: 119,
        date: "2028-05-09",
        port: "Safaga (Luxor)",
        portCode: "SGA",
        country: "Egypt",
        arrive: "08:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 120,
        date: "2028-05-10",
        port: "Safaga (Luxor)",
        portCode: "SGA",
        country: "Egypt",
        depart: "23:00",
        dressCode: "Resort Casual",
      },
      {
        day: 121,
        date: "2028-05-11",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 122,
        date: "2028-05-12",
        port: "Suez Canal Transit",
        portCode: "SZC",
        country: "Egypt",
        dressCode: "Resort Casual",
      },
      {
        day: 123,
        date: "2028-05-13",
        port: "Alexandria",
        portCode: "ALY",
        country: "Egypt",
        arrive: "06:00",
        depart: "23:00",
        dressCode: "Resort Casual",
      },
      {
        day: 124,
        date: "2028-05-14",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 125,
        date: "2028-05-15",
        port: "Souda (Chania)",
        portCode: "GAF",
        country: "Greece",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 126,
        date: "2028-05-16",
        port: "Katakolon (Olympia)",
        portCode: "KAK",
        country: "Greece",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 127,
        date: "2028-05-17",
        port: "Siracusa",
        portCode: "SIR",
        country: "Italy",
        arrive: "10:00",
        depart: "20:00",
        dressCode: "Resort Casual",
      },
      {
        day: 128,
        date: "2028-05-18",
        port: "Valletta",
        portCode: "MLA",
        country: "Malta",
        arrive: "07:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 129,
        date: "2028-05-19",
        port: "Valletta",
        portCode: "MLA",
        country: "Malta",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 130,
        date: "2028-05-20",
        port: "La Goulette (Tunis)",
        portCode: "LGN",
        country: "Tunisia",
        arrive: "08:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 131,
        date: "2028-05-21",
        port: "Trapani",
        portCode: "TPS",
        country: "Italy",
        arrive: "08:00",
        depart: "22:00",
        dressCode: "Resort Casual",
      },
      {
        day: 132,
        date: "2028-05-22",
        port: "Lipari Island",
        portCode: "LIP",
        country: "Italy",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 133,
        date: "2028-05-23",
        port: "Sorrento",
        portCode: "RRO",
        country: "Italy",
        arrive: "08:00",
        depart: "23:00",
        dressCode: "Resort Casual",
      },
      {
        day: 134,
        date: "2028-05-24",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 135,
        date: "2028-05-25",
        port: "Civitavecchia (Rome)",
        portCode: "CVV",
        country: "Italy",
        arrive: "06:00",
        depart: "20:00",
        dressCode: "Resort Casual",
      },
      {
        day: 136,
        date: "2028-05-26",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 137,
        date: "2028-05-27",
        port: "Barcelona",
        portCode: "BCN",
        country: "Spain",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 138,
        date: "2028-05-28",
        port: "Alicante",
        portCode: "ALC",
        country: "Spain",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 139,
        date: "2028-05-29",
        port: "Motril",
        portCode: "MOT",
        country: "Spain",
        arrive: "08:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 140,
        date: "2028-05-30",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 141,
        date: "2028-05-31",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 142,
        date: "2028-06-01",
        port: "Ponta Delgada",
        portCode: "PDL",
        country: "Portugal",
        arrive: "09:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 143,
        date: "2028-06-02",
        port: "Horta",
        portCode: "HOR",
        country: "Portugal",
        arrive: "07:00",
        depart: "14:00",
        dressCode: "Resort Casual",
      },
      {
        day: 144,
        date: "2028-06-03",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 145,
        date: "2028-06-04",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 146,
        date: "2028-06-05",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 147,
        date: "2028-06-06",
        port: "Royal Naval Dockyard",
        portCode: "DND",
        country: "Bermuda",
        arrive: "13:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 148,
        date: "2028-06-07",
        port: "Royal Naval Dockyard",
        portCode: "DND",
        country: "Bermuda",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 149,
        date: "2028-06-08",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 150,
        date: "2028-06-09",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 151,
        date: "2028-06-10",
        port: "Fort Lauderdale",
        portCode: "FLL",
        country: "United States of America",
        dressCode: "Resort Casual",
      },
    ],
    suites: [
      {
        category: "AQUAMARINE VERANDA SUITE",
        categoryCode: "ve",
        priceDouble: 90700,
        priceSingle: 154200,
        priceChild: 49000,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 80,
      },
      {
        category: "SAPPHIRE OCEAN VIEW SUITE",
        categoryCode: "gv",
        priceDouble: 82700,
        priceSingle: 124000,
        priceChild: 40500,
        portCharge: 10900,
        maxCapacity: 3,
        availability: 60,
      },
      {
        category: "JUNIOR CRYSTAL PENTHOUSE SUITE",
        categoryCode: "ro",
        priceDouble: 189100,
        priceSingle: 349800,
        priceChild: 49200,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 0,
      },
      {
        category: "SINGLE GUEST ROOM WITH OCEAN VIEW",
        categoryCode: "os",
        priceDouble: 94500,
        priceSingle: 94500,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 0,
      },
      {
        category: "SAPPHIRE VERANDA SUITE",
        categoryCode: "gx",
        priceDouble: 120100,
        priceSingle: 204200,
        priceChild: 50400,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 45,
      },
      {
        category: "DOUBLE GUEST ROOM WITH VERANDA",
        categoryCode: "oc",
        priceDouble: 81200,
        priceSingle: 146200,
        priceChild: 47100,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 50,
      },
      {
        category: "CRYSTAL PENTHOUSE SUITE",
        categoryCode: "ow",
        priceDouble: 270100,
        priceSingle: 499700,
        priceChild: 54000,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 0,
      },
      {
        category: "DOUBLE GUEST ROOM WITH OCEAN VIEW",
        categoryCode: "ov",
        priceDouble: 61600,
        priceSingle: 104700,
        priceChild: 36300,
        portCharge: 10900,
        maxCapacity: 2,
        availability: 65,
      },
    ],
  },
  {
    year: 2029,
    code: "CSY-W127-290107",
    voyageId: 11156,
    title: "Melbourne to New York City",
    ship: "Crystal Symphony",
    shipCode: "CSY",
    nights: 127,
    embarkDate: "2029-01-07",
    debarkDate: "2029-05-13",
    embarkPort: "Melbourne",
    debarkPort: "New York",
    countries: 22,
    priceFrom: 69000,
    currency: "USD",
    media: {
      hero: "https://stcontentprodeastus001.blob.core.windows.net/ecm/laura-cros-xLvkzpsKIms-unsplash (1)-43641292-6eb7-48c0-a9b5-796b578af220.jpg",
      gallery: [
        "https://stcontentprodeastus001.blob.core.windows.net/ecm/w127_square-6b9202fb-d6d4-4875-804d-d621008be158.png",
      ],
      mapSvg: "https://stcontentprodeastus001.blob.core.windows.net/ecm/maps/Images/225487.svg",
      mapPng: "https://stcontentprodeastus001.blob.core.windows.net/ecm/maps/Images/225488.png",
      itineraryPdf: "[object Object]",
    },
    sourceUrl: "https://www.crystalcruises.com/cruises/none-csy-w127-290107",
    itinerary: [
      {
        day: 1,
        date: "2029-01-07",
        port: "Melbourne",
        portCode: "MEL",
        country: "Australia",
        depart: "21:00",
        dressCode: "Resort Casual",
      },
      {
        day: 2,
        date: "2029-01-08",
        port: "Portland",
        portCode: "PTJ",
        country: "Australia",
        arrive: "11:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 3,
        date: "2029-01-09",
        port: "Kangaroo Island",
        portCode: "KAG",
        country: "Australia",
        arrive: "12:00",
        depart: "20:00",
        dressCode: "Resort Casual",
      },
      {
        day: 4,
        date: "2029-01-10",
        port: "Adelaide",
        portCode: "ADL",
        country: "Australia",
        arrive: "08:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 5,
        date: "2029-01-11",
        port: "Adelaide",
        portCode: "ADL",
        country: "Australia",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 6,
        date: "2029-01-12",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 7,
        date: "2029-01-13",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 8,
        date: "2029-01-14",
        port: "Esperance",
        portCode: "EPR",
        country: "Australia",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 9,
        date: "2029-01-15",
        port: "Albany",
        portCode: "ALH",
        country: "Australia",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 10,
        date: "2029-01-16",
        port: "Busselton",
        portCode: "BUS",
        country: "Australia",
        arrive: "10:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 11,
        date: "2029-01-17",
        port: "Fremantle (Perth)",
        portCode: "FRE",
        country: "Australia",
        arrive: "08:00",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 12,
        date: "2029-01-18",
        port: "Fremantle (Perth)",
        portCode: "FRE",
        country: "Australia",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 13,
        date: "2029-01-19",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 14,
        date: "2029-01-20",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 15,
        date: "2029-01-21",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 16,
        date: "2029-01-22",
        port: "Rinca",
        portCode: "RCA",
        country: "Indonesia",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 17,
        date: "2029-01-23",
        port: "Benoa (Bali)",
        portCode: "BOA",
        country: "Indonesia",
        arrive: "12:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 18,
        date: "2029-01-24",
        port: "Benoa (Bali)",
        portCode: "BOA",
        country: "Indonesia",
        arrive: "00:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 19,
        date: "2029-01-25",
        port: "Waingapu, Sumba",
        portCode: "WGP",
        country: "Indonesia",
        arrive: "12:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 20,
        date: "2029-01-26",
        port: "Kupang",
        portCode: "KOE",
        country: "Indonesia",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 21,
        date: "2029-01-27",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 22,
        date: "2029-01-28",
        port: "Darwin",
        portCode: "DRW",
        country: "Australia",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 23,
        date: "2029-01-29",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 24,
        date: "2029-01-30",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 25,
        date: "2029-01-31",
        port: "Cairns",
        portCode: "CNS",
        country: "Australia",
        arrive: "15:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 26,
        date: "2029-02-01",
        port: "Cairns",
        portCode: "CNS",
        country: "Australia",
        arrive: "00:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 27,
        date: "2029-02-02",
        port: "Airlie Beach",
        portCode: "WSY",
        country: "Australia",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 28,
        date: "2029-02-03",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 29,
        date: "2029-02-04",
        port: "Brisbane",
        portCode: "BNE",
        country: "Australia",
        arrive: "07:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 30,
        date: "2029-02-05",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 31,
        date: "2029-02-06",
        port: "Sydney",
        portCode: "SYD",
        country: "Australia",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 32,
        date: "2029-02-07",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 33,
        date: "2029-02-08",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 34,
        date: "2029-02-09",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 35,
        date: "2029-02-10",
        port: "Wellington",
        portCode: "WLG",
        country: "New Zealand",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 36,
        date: "2029-02-11",
        port: "Gisborne",
        portCode: "GIS",
        country: "New Zealand",
        arrive: "10:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 37,
        date: "2029-02-12",
        port: "Tauranga",
        portCode: "TRG",
        country: "New Zealand",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 38,
        date: "2029-02-13",
        port: "Auckland",
        portCode: "AKL",
        country: "New Zealand",
        arrive: "08:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 39,
        date: "2029-02-14",
        port: "Auckland",
        portCode: "AKL",
        country: "New Zealand",
        arrive: "00:00",
        dressCode: "Resort Casual",
      },
      {
        day: 40,
        date: "2029-02-15",
        port: "Bay of Islands",
        portCode: "BAY",
        country: "New Zealand",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 41,
        date: "2029-02-16",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 42,
        date: "2029-02-17",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 43,
        date: "2029-02-18",
        port: "Suva",
        portCode: "SUV",
        country: "Fiji",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 44,
        date: "2029-02-19",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 45,
        date: "2029-02-20",
        port: "Apia",
        portCode: "APW",
        country: "Samoa Islands",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 45,
        date: "2029-02-20",
        port: "Pago Pago",
        portCode: "PPG",
        country: "American samoa",
        arrive: "08:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 46,
        date: "2029-02-20",
        port: "International Date Line - Gain a Day",
        portCode: "C15",
        dressCode: "Resort Casual",
      },
      {
        day: 47,
        date: "2029-02-21",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 48,
        date: "2029-02-22",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 49,
        date: "2029-02-23",
        port: "Raiatea",
        portCode: "RFP",
        country: "French Polynesia",
        arrive: "10:00",
        depart: "23:00",
        dressCode: "Resort Casual",
      },
      {
        day: 50,
        date: "2029-02-24",
        port: "Bora Bora",
        portCode: "BOB",
        country: "French Polynesia",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 51,
        date: "2029-02-25",
        port: "Moorea Island",
        portCode: "MOZ",
        country: "French Polynesia",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 51,
        date: "2029-02-25",
        port: "Papeete (Tahiti)",
        portCode: "PPT",
        country: "French Polynesia",
        arrive: "20:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 52,
        date: "2029-02-26",
        port: "Papeete (Tahiti)",
        portCode: "PPT",
        country: "French Polynesia",
        arrive: "00:00",
        depart: "23:00",
        dressCode: "Resort Casual",
      },
      {
        day: 53,
        date: "2029-02-27",
        port: "Huahine",
        portCode: "HUH",
        country: "French Polynesia",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 54,
        date: "2029-02-28",
        port: "Rangiroa",
        portCode: "RGI",
        country: "French Polynesia",
        arrive: "09:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 55,
        date: "2029-03-01",
        port: "Fakarava",
        portCode: "FAV",
        country: "French Polynesia",
        arrive: "07:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 56,
        date: "2029-03-02",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 57,
        date: "2029-03-03",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 58,
        date: "2029-03-04",
        port: "Adamstown",
        portCode: "PCN",
        country: "Pitcairn Island",
        arrive: "08:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 59,
        date: "2029-03-05",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 60,
        date: "2029-03-06",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 61,
        date: "2029-03-07",
        port: "Hanga Roa (Easter Island)",
        portCode: "IPC",
        country: "Chile",
        arrive: "13:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 62,
        date: "2029-03-08",
        port: "Hanga Roa (Easter Island)",
        portCode: "IPC",
        country: "Chile",
        arrive: "00:00",
        depart: "14:00",
        dressCode: "Resort Casual",
      },
      {
        day: 63,
        date: "2029-03-09",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 64,
        date: "2029-03-10",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 65,
        date: "2029-03-11",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 66,
        date: "2029-03-12",
        port: "Robinson Crusoe Island",
        portCode: "RBI",
        country: "Chile",
        arrive: "11:00",
        depart: "20:00",
        dressCode: "Resort Casual",
      },
      {
        day: 67,
        date: "2029-03-13",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 68,
        date: "2029-03-14",
        port: "Valparaiso",
        portCode: "VAP",
        country: "Chile",
        arrive: "07:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 69,
        date: "2029-03-15",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 70,
        date: "2029-03-16",
        port: "Puerto Montt",
        portCode: "PMC",
        country: "Chile",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 71,
        date: "2029-03-17",
        port: "Castro",
        portCode: "WCA",
        country: "Chile",
        arrive: "08:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 72,
        date: "2029-03-18",
        port: "Puerto Chacabuco",
        portCode: "PCH",
        country: "Chile",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 73,
        date: "2029-03-19",
        port: "Laguna San Rafael",
        portCode: "LSR",
        country: "Chile",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 74,
        date: "2029-03-20",
        port: "Cruising the Chilean Fjords",
        portCode: "C01",
        country: "Chile",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 75,
        date: "2029-03-21",
        port: "Cruising the Chilean Fjords",
        portCode: "C01",
        country: "Chile",
        dressCode: "Resort Casual",
      },
      {
        day: 76,
        date: "2029-03-22",
        port: "Punta Arenas",
        portCode: "PUQ",
        country: "Chile",
        arrive: "07:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 77,
        date: "2029-03-23",
        port: "Ushuaia",
        portCode: "USH",
        country: "Argentina",
        arrive: "19:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 78,
        date: "2029-03-24",
        port: "Ushuaia",
        portCode: "USH",
        country: "Argentina",
        arrive: "00:00",
        depart: "20:00",
        dressCode: "Resort Casual",
      },
      {
        day: 79,
        date: "2029-03-25",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 80,
        date: "2029-03-26",
        port: "Port Stanley",
        portCode: "PSY",
        country: "Falkland Islands (Malvinas)",
        arrive: "07:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 81,
        date: "2029-03-27",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 82,
        date: "2029-03-28",
        port: "Puerto Madryn",
        portCode: "PMY",
        country: "Argentina",
        arrive: "08:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 83,
        date: "2029-03-29",
        port: "Puerto Madryn",
        portCode: "PMY",
        country: "Argentina",
        arrive: "00:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 84,
        date: "2029-03-30",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 85,
        date: "2029-03-31",
        port: "Punta del Este",
        portCode: "PDP",
        country: "Uruguay",
        arrive: "10:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 86,
        date: "2029-04-01",
        port: "Buenos Aires",
        portCode: "BUE",
        country: "Argentina",
        arrive: "09:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 87,
        date: "2029-04-02",
        port: "Buenos Aires",
        portCode: "BUE",
        country: "Argentina",
        arrive: "00:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 88,
        date: "2029-04-03",
        port: "Montevideo",
        portCode: "MVD",
        country: "Uruguay",
        arrive: "08:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 89,
        date: "2029-04-04",
        port: "Montevideo",
        portCode: "MVD",
        country: "Uruguay",
        arrive: "00:00",
        depart: "13:00",
        dressCode: "Resort Casual",
      },
      {
        day: 90,
        date: "2029-04-05",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 91,
        date: "2029-04-06",
        port: "Balneário Camboriú",
        portCode: "BAC",
        country: "Brazil",
        arrive: "07:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 92,
        date: "2029-04-07",
        port: "Ilhabela",
        portCode: "IBE",
        country: "Brazil",
        arrive: "09:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 93,
        date: "2029-04-08",
        port: "Paraty",
        portCode: "PAT",
        country: "Brazil",
        arrive: "07:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 94,
        date: "2029-04-09",
        port: "Rio de Janeiro",
        portCode: "RIO",
        country: "Brazil",
        arrive: "07:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 95,
        date: "2029-04-10",
        port: "Rio de Janeiro",
        portCode: "RIO",
        country: "Brazil",
        arrive: "00:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 96,
        date: "2029-04-11",
        port: "Búzios",
        portCode: "BZC",
        country: "Brazil",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 97,
        date: "2029-04-12",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 98,
        date: "2029-04-13",
        port: "Salvador de Bahia",
        portCode: "SSA",
        country: "Brazil",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 99,
        date: "2029-04-14",
        port: "Maceio",
        portCode: "MCZ",
        country: "Brazil",
        arrive: "11:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 100,
        date: "2029-04-15",
        port: "Recife",
        portCode: "REC",
        country: "Brazil",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 101,
        date: "2029-04-16",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 102,
        date: "2029-04-17",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 103,
        date: "2029-04-18",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 104,
        date: "2029-04-19",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 105,
        date: "2029-04-20",
        port: "Santarém",
        portCode: "STM",
        country: "Brazil",
        arrive: "10:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 106,
        date: "2029-04-21",
        port: "Boca Da Valeria",
        portCode: "BO1",
        country: "Brazil",
        arrive: "07:00",
        depart: "15:00",
        dressCode: "Resort Casual",
      },
      {
        day: 107,
        date: "2029-04-22",
        port: "Manaus (Amazon Rainforest)",
        portCode: "MAO",
        country: "Brazil",
        arrive: "10:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 108,
        date: "2029-04-23",
        port: "Manaus (Amazon Rainforest)",
        portCode: "MAO",
        country: "Brazil",
        arrive: "00:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 109,
        date: "2029-04-24",
        port: "Parintins",
        portCode: "PIN",
        country: "Brazil",
        arrive: "10:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 110,
        date: "2029-04-25",
        port: "Alter do Chão",
        portCode: "ALT",
        country: "Brazil",
        arrive: "09:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 111,
        date: "2029-04-26",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 112,
        date: "2029-04-27",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 113,
        date: "2029-04-28",
        port: "Iles du Salut (Devil`s Island)",
        portCode: "DVI",
        country: "French Guiana",
        arrive: "08:00",
        depart: "16:00",
        dressCode: "Resort Casual",
      },
      {
        day: 114,
        date: "2029-04-29",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 115,
        date: "2029-04-30",
        port: "Bridgetown",
        portCode: "BGI",
        country: "Barbados",
        arrive: "06:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 116,
        date: "2029-05-01",
        port: "Roseau",
        portCode: "RSU",
        country: "Dominica",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 117,
        date: "2029-05-02",
        port: "Basseterre",
        portCode: "BAS",
        country: "St Kitts and Nevis",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 118,
        date: "2029-05-03",
        port: "San Juan",
        portCode: "SJU",
        country: "Puerto Rico",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 119,
        date: "2029-05-04",
        port: "Samana",
        portCode: "SAM",
        country: "Dominican Republic",
        arrive: "08:00",
        depart: "18:00",
        dressCode: "Resort Casual",
      },
      {
        day: 120,
        date: "2029-05-05",
        port: "Grand Turk",
        portCode: "GDT",
        country: "Turks and Caicos Islands",
        arrive: "08:00",
        depart: "17:00",
        dressCode: "Resort Casual",
      },
      {
        day: 121,
        date: "2029-05-06",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 122,
        date: "2029-05-07",
        port: "Fort Lauderdale",
        portCode: "FLL",
        country: "United States of America",
        arrive: "07:00",
        depart: "19:00",
        dressCode: "Resort Casual",
      },
      {
        day: 123,
        date: "2029-05-08",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 124,
        date: "2029-05-09",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 125,
        date: "2029-05-10",
        port: "Royal Naval Dockyard",
        portCode: "DND",
        country: "Bermuda",
        arrive: "09:00",
        depart: "23:59",
        overnight: true,
        dressCode: "Resort Casual",
      },
      {
        day: 126,
        date: "2029-05-11",
        port: "Royal Naval Dockyard",
        portCode: "DND",
        country: "Bermuda",
        arrive: "00:00",
        depart: "14:00",
        dressCode: "Resort Casual",
      },
      {
        day: 127,
        date: "2029-05-12",
        port: "Day at sea",
        portCode: "C36",
        dressCode: "Resort Casual",
      },
      {
        day: 128,
        date: "2029-05-13",
        port: "New York City",
        portCode: "NYC",
        country: "United States of America",
        arrive: "07:00",
        dressCode: "Resort Casual",
      },
    ],
    suites: [
      {
        category: "DOUBLE GUEST ROOM WITH VERANDA",
        categoryCode: "oc",
        priceDouble: 75100,
        priceSingle: 125100,
        priceChild: 45400,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 85,
      },
      {
        category: "SINGLE GUEST ROOM WITH OCEAN VIEW",
        categoryCode: "os",
        priceDouble: 82100,
        priceSingle: 82100,
        priceChild: 4000,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 10,
      },
      {
        category: "SAPPHIRE OCEAN VIEW SUITE",
        categoryCode: "gv",
        priceDouble: 78100,
        priceSingle: 115100,
        priceChild: 40200,
        portCharge: 10900,
        maxCapacity: 3,
        availability: 170,
      },
      {
        category: "AQUAMARINE VERANDA SUITE",
        categoryCode: "ve",
        priceDouble: 85100,
        priceSingle: 134100,
        priceChild: 48000,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 215,
      },
      {
        category: "CRYSTAL PENTHOUSE SUITE",
        categoryCode: "ow",
        priceDouble: 270100,
        priceSingle: 509100,
        priceChild: 55900,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 5,
      },
      {
        category: "JUNIOR CRYSTAL PENTHOUSE SUITE",
        categoryCode: "ro",
        priceDouble: 181100,
        priceSingle: 341100,
        priceChild: 50800,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 0,
      },
      {
        category: "SAPPHIRE VERANDA SUITE",
        categoryCode: "gx",
        priceDouble: 115100,
        priceSingle: 181100,
        priceChild: 51100,
        portCharge: 10900,
        maxCapacity: 4,
        availability: 215,
      },
      {
        category: "DOUBLE GUEST ROOM WITH OCEAN VIEW",
        categoryCode: "ov",
        priceDouble: 58100,
        priceSingle: 90100,
        priceChild: 35600,
        portCharge: 10900,
        maxCapacity: 2,
        availability: 190,
      },
    ],
  },
];
