import type { ComponentKind, NormalizedComponent, SupplierRegistration, TripRequirements } from "./types";

export interface RankingWeights { feasibility:number; luxury:number; price:number; budget:number; flexibility:number; reliability:number; geography:number; time:number; margin:number; preference:number; }
export const DEFAULT_RANKING_WEIGHTS: RankingWeights = { feasibility:0.22, luxury:0.14, price:0.12, budget:0.08, flexibility:0.08, reliability:0.10, geography:0.08, time:0.07, margin:0.06, preference:0.05 };
export interface RankingProfile { weights?: Partial<RankingWeights>; kindPreferences?: Partial<Record<ComponentKind, number>>; interests?: string[]; }
export interface PackageOptimizationInput { id:string; items:NormalizedComponent[]; total:number; marginAmount?:number; }
export interface PackageOptimizationMetrics { geography:number; time:number; margin:number; preference:number; }
export function resolveRankingWeights(profile?: RankingProfile): RankingWeights { const merged={...DEFAULT_RANKING_WEIGHTS,...(profile?.weights??{})}; const total=Object.values(merged).reduce((s,v)=>s+Math.max(0,v),0)||1; return Object.fromEntries(Object.entries(merged).map(([k,v])=>[k,Math.max(0,v)/total])) as RankingWeights; }
export function componentPreference(c:NormalizedComponent, profile:RankingProfile={}):number { const kind=profile.kindPreferences?.[c.kind]??0.5; const terms=(profile.interests??[]).map(x=>x.trim().toLowerCase()).filter(Boolean); const title=c.title.toLowerCase(); const interestFit=terms.length?terms.filter(x=>title.includes(x)).length/terms.length:0.5; return Math.max(0,Math.min(1,(kind+interestFit)/2)); }
export function packageOptimizationMetrics(input:PackageOptimizationInput, req:TripRequirements, registry:Map<string,SupplierRegistration>, profile:RankingProfile={}):PackageOptimizationMetrics {
 const places=new Set(req.destinations.map(x=>x.toLowerCase())); const covered=new Set<string>(); for(const c of input.items){if(places.has(c.start.place.toLowerCase()))covered.add(c.start.place.toLowerCase());if(places.has(c.end.place.toLowerCase()))covered.add(c.end.place.toLowerCase());}
 const geography=places.size?covered.size/places.size:1; const sorted=[...input.items].sort((a,b)=>Date.parse(a.start.at)-Date.parse(b.start.at)); const gaps:number[]=[]; for(let i=1;i<sorted.length;i++){const gap=(Date.parse(sorted[i]!.start.at)-Date.parse(sorted[i-1]!.end.at))/3600000;if(gap>=0)gaps.push(gap);} const time=gaps.length?gaps.reduce((s,g)=>s+Math.max(0,Math.min(1,1-Math.abs(g-2)/24)),0)/gaps.length:1;
 const net=input.items.reduce((s,c)=>s+c.net.amount,0); const marginAmount=input.marginAmount??Math.max(0,input.total-net); const margin=input.total>0?Math.max(0,Math.min(1,marginAmount/input.total)):0; const preference=input.items.length?input.items.reduce((s,c)=>s+componentPreference(c,profile),0)/input.items.length:0; void registry; return {geography,time,margin,preference};
}
export function rankComponents(components:NormalizedComponent[], req:TripRequirements, registry:Map<string,SupplierRegistration>, profile:RankingProfile={}):NormalizedComponent[] { const places=new Set(req.destinations.map(x=>x.toLowerCase())); const score=(c:NormalizedComponent)=>{const quality=(c.quality??3)/5;const luxury=1-Math.abs(quality*5-req.luxuryLevel)/5;const geography=places.size?Number(places.has(c.start.place.toLowerCase())||places.has(c.end.place.toLowerCase())):1;const reliability=registry.get(c.supplierKey)?.reliability??0;const preference=componentPreference(c,profile);return .30*luxury+.20*reliability+.20*geography+.30*preference;}; return [...components].sort((a,b)=>score(b)-score(a)); }