// DEMONSTRATION CONTENT — internal sample records used until authorised
// partner credentials are supplied. Every record is flagged
// `dataSource: "demonstration"` and is badged in the UI. When a connector
// receives credentials the runtime replaces these records with normalised
// partner-API journeys; no UI, search, filter or booking code changes.
import { images } from "../data-images";
import type { Journey } from "./types";

function departures(
  seed: string[],
  price: number,
  currency = "USD",
  days = 12,
): Journey["departures"] {
  return seed.map((date, i) => {
    const end = new Date(date);
    end.setDate(end.getDate() + days);
    const availability = i === 0 ? "limited" : i === seed.length - 1 ? "waitlist" : "available";
    return {
      date,
      endDate: end.toISOString().slice(0, 10),
      price: price + i * 450,
      currency,
      availability: availability as Journey["departures"][number]["availability"],
      seatsRemaining: availability === "limited" ? 4 : availability === "waitlist" ? 0 : 12,
    };
  });
}

const TERMS = [
  "Deposit of 20% secures the reservation; balance due 90 days before departure.",
  "Prices are per guest based on double occupancy and exclude international air unless stated.",
  "Cancellation and amendment charges follow the operating partner's published schedule.",
];

export const DEMO_JOURNEYS: Journey[] = [
  {
    code: "AK-EGY-1201",
    title: "Egypt & the Nile by Private Dahabiya",
    subtitle: "Cairo, Luxor and Aswan with Egyptologist-led private access",
    partnerId: "abercrombie-kent",
    partnerName: "Abercrombie & Kent",
    collection: "Ultra-Luxury Tours",
    collectionKind: "tours",
    region: "Africa",
    regionSlug: "africa",
    country: "Egypt",
    countrySlug: "egypt",
    cities: ["Cairo", "Luxor", "Aswan"],
    destinationSlugs: ["cairo", "luxor", "aswan"],
    durationDays: 11,
    durationNights: 10,
    priceFrom: 14850,
    currency: "USD",
    groupSizeMax: 12,
    groupStyle: "small-group",
    luxuryLevel: "ultra-luxury",
    hotels: [
      "Four Seasons Cairo at Nile Plaza",
      "Sofitel Winter Palace Luxor",
      "Sofitel Legend Old Cataract Aswan",
    ],
    ships: ["Private dahabiya Amoura"],
    rail: [],
    mealPlan: "Full board on the Nile, breakfast and selected dinners on land",
    highlights: [
      "After-hours private access to the Great Pyramid complex",
      "Grand Egyptian Museum with a resident Egyptologist",
      "Four nights aboard a chartered dahabiya sailing Esna to Aswan",
      "Private felucca sundowner beneath the Old Cataract",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrive Cairo",
        location: "Cairo",
        description:
          "Private transfer and Nile-view suite; evening briefing with your Resident Tour Director.",
        meals: ["Dinner"],
        accommodation: "Four Seasons Cairo at Nile Plaza",
      },
      {
        day: 2,
        title: "Pyramids & Grand Egyptian Museum",
        location: "Giza",
        description:
          "Private early access to Giza before the crowds, followed by curator-led galleries at the GEM.",
        meals: ["Breakfast", "Lunch"],
        accommodation: "Four Seasons Cairo at Nile Plaza",
      },
      {
        day: 3,
        title: "Fly to Luxor",
        location: "Luxor",
        description:
          "Karnak by night with private illumination and a horse-drawn corniche arrival.",
        meals: ["Breakfast", "Dinner"],
        accommodation: "Sofitel Winter Palace",
      },
      {
        day: 4,
        title: "Valley of the Kings",
        location: "West Bank",
        description:
          "Tombs of Seti I and Nefertari with private permits, then board your dahabiya at Esna.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Dahabiya Amoura",
      },
      {
        day: 7,
        title: "Sailing to Aswan",
        location: "Nile",
        description: "Slow sailing days with village visits at El Kab and Gebel Silsila.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Dahabiya Amoura",
      },
      {
        day: 11,
        title: "Depart Aswan",
        location: "Aswan",
        description: "Philae Temple at sunrise before your onward flight.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: [
      "Resident Tour Director throughout",
      "All internal flights",
      "Private guiding and permits",
      "Chartered dahabiya on full board",
      "All transfers and gratuities",
    ],
    exclusions: ["International flights", "Travel insurance", "Egypt visa", "Personal expenses"],
    extensions: [
      { title: "Abu Simbel by private charter", nights: 1, priceFrom: 2400 },
      { title: "El Gouna Red Sea finale", nights: 3, priceFrom: 3100 },
    ],
    departures: departures(
      ["2026-10-12", "2026-11-09", "2027-01-18", "2027-03-08"],
      14850,
      "USD",
      10,
    ),
    media: {
      hero: images.africa,
      gallery: [images.africa, images.middleEast, images.hero],
      brochureUrl: "#brochure",
    },
    terms: TERMS,
    reviews: [
      {
        author: "H. Mehta",
        rating: 5,
        title: "Faultless from start to finish",
        body: "The private pyramid access alone justified the journey; the dahabiya was extraordinary.",
        date: "2026-03-04",
      },
      {
        author: "C. Laurent",
        rating: 4.8,
        title: "Egyptology at its best",
        body: "Our guide's knowledge transformed every site.",
        date: "2026-02-11",
      },
    ],
    rating: 4.9,
    reviewCount: 128,
    interests: ["Culture & heritage", "Culinary", "Romance"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "AK-BOT-0844",
    title: "Botswana Under Canvas",
    subtitle: "Okavango Delta, Linyanti and Chobe by light aircraft",
    partnerId: "abercrombie-kent",
    partnerName: "Abercrombie & Kent",
    collection: "Safari",
    collectionKind: "safari",
    region: "Africa",
    regionSlug: "africa",
    country: "Botswana",
    countrySlug: "botswana",
    cities: ["Maun", "Okavango Delta", "Chobe"],
    destinationSlugs: ["okavango-delta", "chobe"],
    durationDays: 9,
    durationNights: 8,
    priceFrom: 18600,
    currency: "USD",
    groupSizeMax: 8,
    groupStyle: "private",
    luxuryLevel: "ultra-luxury",
    hotels: ["Sanctuary Chief's Camp", "Sanctuary Stanley's Camp", "Sanctuary Chobe Chilwero"],
    ships: [],
    rail: [],
    mealPlan: "Fully inclusive with premium beverages",
    highlights: [
      "Mokoro safaris through Delta channels",
      "Predator research drives in Linyanti",
      "Chobe river cruise at golden hour",
      "Private guide and vehicle throughout",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrive Maun",
        location: "Maun",
        description: "Light-aircraft transfer into the Delta.",
        meals: ["Lunch", "Dinner"],
        accommodation: "Sanctuary Chief's Camp",
      },
      {
        day: 3,
        title: "Okavango water safaris",
        location: "Okavango Delta",
        description: "Mokoro and motorboat exploration with walking safaris on Chief's Island.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Sanctuary Chief's Camp",
      },
      {
        day: 5,
        title: "Linyanti concession",
        location: "Linyanti",
        description: "Wild-dog and big-cat tracking on a private concession.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Sanctuary Stanley's Camp",
      },
      {
        day: 7,
        title: "Chobe",
        location: "Chobe",
        description: "Elephant herds at the river; sunset cruise.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Sanctuary Chobe Chilwero",
      },
      {
        day: 9,
        title: "Depart via Victoria Falls",
        location: "Victoria Falls",
        description: "Road transfer and departure.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: [
      "All light-aircraft transfers",
      "Private guide and vehicle",
      "All meals and premium drinks",
      "Park fees and conservation levies",
    ],
    exclusions: ["International flights", "Visas", "Insurance"],
    extensions: [{ title: "Victoria Falls at Royal Livingstone", nights: 2, priceFrom: 2650 }],
    departures: departures(
      ["2026-09-05", "2026-10-03", "2027-05-16", "2027-07-11"],
      18600,
      "USD",
      8,
    ),
    media: {
      hero: images.africa,
      gallery: [images.africa, images.smallGroup],
      brochureUrl: "#brochure",
    },
    terms: TERMS,
    reviews: [
      {
        author: "J. Whitfield",
        rating: 5,
        title: "The Delta at its purest",
        body: "Three distinct ecosystems in eight nights, flawlessly connected.",
        date: "2026-06-02",
      },
    ],
    rating: 4.9,
    reviewCount: 96,
    interests: ["Wildlife", "Adventure"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "AK-IND-0450",
    title: "Rajasthan Palaces & Private Residences",
    subtitle: "Delhi, Jaipur, Jodhpur and Udaipur with royal hosts",
    partnerId: "abercrombie-kent",
    partnerName: "Abercrombie & Kent",
    collection: "Cultural & Heritage",
    collectionKind: "cultural",
    region: "Asia",
    regionSlug: "asia",
    country: "India",
    countrySlug: "india",
    cities: ["Delhi", "Jaipur", "Jodhpur", "Udaipur"],
    destinationSlugs: ["delhi", "jaipur", "udaipur"],
    durationDays: 12,
    durationNights: 11,
    priceFrom: 11400,
    currency: "USD",
    groupSizeMax: 10,
    groupStyle: "private",
    luxuryLevel: "luxury",
    hotels: ["The Oberoi New Delhi", "Rambagh Palace", "Umaid Bhawan Palace", "Taj Lake Palace"],
    ships: [],
    rail: [],
    mealPlan: "Breakfast daily and selected private dinners",
    highlights: [
      "Private dinner hosted at a working royal residence",
      "Taj Mahal at sunrise with a heritage guide",
      "Blue City rooftop tasting menu",
      "Vintage-car arrival in Udaipur",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrive Delhi",
        location: "Delhi",
        description: "Old Delhi heritage walk and Sufi music at Nizamuddin.",
        meals: ["Dinner"],
        accommodation: "The Oberoi New Delhi",
      },
      {
        day: 4,
        title: "Jaipur",
        location: "Jaipur",
        description: "Amber Fort before opening and a private audience at the City Palace.",
        meals: ["Breakfast", "Dinner"],
        accommodation: "Rambagh Palace",
      },
      {
        day: 7,
        title: "Jodhpur",
        location: "Jodhpur",
        description: "Mehrangarh Fort and the artisans of the Blue City.",
        meals: ["Breakfast"],
        accommodation: "Umaid Bhawan Palace",
      },
      {
        day: 10,
        title: "Udaipur",
        location: "Udaipur",
        description: "Lake Pichola at dusk aboard a private launch.",
        meals: ["Breakfast", "Dinner"],
        accommodation: "Taj Lake Palace",
      },
      {
        day: 12,
        title: "Depart",
        location: "Udaipur",
        description: "Transfer for onward flights.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: [
      "Private car and chauffeur throughout",
      "Local specialist guides",
      "Monument fees",
      "Domestic flights",
    ],
    exclusions: ["International flights", "India e-visa", "Insurance"],
    extensions: [{ title: "Ranthambore tiger safari", nights: 2, priceFrom: 1980 }],
    departures: departures(
      ["2026-10-20", "2026-12-01", "2027-02-14", "2027-03-22"],
      11400,
      "USD",
      11,
    ),
    media: { hero: images.india, gallery: [images.india, images.asia] },
    terms: TERMS,
    reviews: [
      {
        author: "S. Kapoor",
        rating: 4.8,
        title: "Access money can't usually buy",
        body: "The private residence dinner was the highlight of our year.",
        date: "2026-04-18",
      },
    ],
    rating: 4.8,
    reviewCount: 74,
    interests: ["Culture & heritage", "Culinary"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "CR-MED-2207",
    title: "Mediterranean Icons aboard Crystal Serenity",
    subtitle: "Barcelona to Athens with all-inclusive butler service",
    partnerId: "crystal-cruises",
    partnerName: "Crystal Cruises",
    collection: "Luxury Cruises",
    collectionKind: "cruises",
    region: "Europe",
    regionSlug: "europe",
    country: "Spain",
    countrySlug: "spain",
    cities: ["Barcelona", "Palma", "Rome", "Santorini", "Athens"],
    destinationSlugs: ["barcelona", "rome", "santorini", "athens"],
    durationDays: 12,
    durationNights: 11,
    priceFrom: 9450,
    currency: "USD",
    groupSizeMax: 740,
    groupStyle: "charter",
    luxuryLevel: "luxury",
    hotels: [],
    ships: ["Crystal Serenity"],
    rail: [],
    mealPlan: "All-inclusive dining with Umi Uma and Osteria d'Ovidio",
    highlights: [
      "All-suite accommodation with butler service",
      "Overnight in Santorini",
      "Crystal Adventures shore programme",
      "Included fine wines, spirits and gratuities",
    ],
    itinerary: [
      {
        day: 1,
        title: "Embark Barcelona",
        location: "Barcelona",
        description: "Board Crystal Serenity and sail at dusk past Montjuïc.",
        meals: ["Dinner"],
        accommodation: "Crystal Serenity",
      },
      {
        day: 3,
        title: "Palma de Mallorca",
        location: "Palma",
        description: "Tramuntana estates and a private cathedral visit.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Crystal Serenity",
      },
      {
        day: 6,
        title: "Civitavecchia for Rome",
        location: "Rome",
        description: "Vatican Museums before opening hours.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Crystal Serenity",
      },
      {
        day: 9,
        title: "Santorini overnight",
        location: "Santorini",
        description: "Caldera sailing and an Oia winery dinner ashore.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Crystal Serenity",
      },
      {
        day: 12,
        title: "Disembark Athens",
        location: "Athens",
        description: "Transfer to Athens airport or extend in the city.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: [
      "All-suite accommodation",
      "All dining including specialty restaurants",
      "Premium beverages",
      "Gratuities",
      "One shore excursion per port",
    ],
    exclusions: ["Flights", "Pre/post hotel nights", "Spa treatments"],
    extensions: [{ title: "Athens Riviera at Four Seasons Astir", nights: 3, priceFrom: 2450 }],
    departures: departures(
      ["2026-09-14", "2026-10-08", "2027-05-04", "2027-06-12"],
      9450,
      "USD",
      11,
    ),
    media: {
      hero: images.cruise,
      gallery: [images.cruise, images.europe],
      brochureUrl: "#brochure",
    },
    terms: TERMS,
    reviews: [
      {
        author: "R. Delgado",
        rating: 4.9,
        title: "Space-per-guest is unmatched",
        body: "Crystal's all-inclusive really is all-inclusive.",
        date: "2026-05-30",
      },
    ],
    rating: 4.9,
    reviewCount: 212,
    interests: ["Culinary", "Culture & heritage", "Beach & islands"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "CR-JPN-3315",
    title: "Japan in Cherry Blossom aboard Crystal Symphony",
    subtitle: "Tokyo to Osaka with Setouchi island calls",
    partnerId: "crystal-cruises",
    partnerName: "Crystal Cruises",
    collection: "Luxury Cruises",
    collectionKind: "cruises",
    region: "Asia",
    regionSlug: "asia",
    country: "Japan",
    countrySlug: "japan",
    cities: ["Tokyo", "Shimizu", "Hiroshima", "Kyoto", "Osaka"],
    destinationSlugs: ["tokyo", "kyoto"],
    durationDays: 10,
    durationNights: 9,
    priceFrom: 11200,
    currency: "USD",
    groupSizeMax: 606,
    groupStyle: "charter",
    luxuryLevel: "luxury",
    hotels: [],
    ships: ["Crystal Symphony"],
    rail: [],
    mealPlan: "All-inclusive with Nobu-trained Umi Uma kitchen",
    highlights: [
      "Sakura season timing",
      "Mount Fuji from Shimizu",
      "Private tea ceremony in Kyoto",
      "Miyajima's floating torii",
    ],
    itinerary: [
      {
        day: 1,
        title: "Embark Tokyo",
        location: "Tokyo",
        description: "Board at Yokohama with a Ginza pre-cruise option.",
        meals: ["Dinner"],
        accommodation: "Crystal Symphony",
      },
      {
        day: 3,
        title: "Shimizu",
        location: "Shimizu",
        description: "Fuji views and a wasabi-farm lunch.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Crystal Symphony",
      },
      {
        day: 6,
        title: "Hiroshima & Miyajima",
        location: "Hiroshima",
        description: "Peace Memorial and the floating torii at high tide.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Crystal Symphony",
      },
      {
        day: 8,
        title: "Kobe for Kyoto",
        location: "Kyoto",
        description: "Private machiya tea ceremony and Arashiyama at dawn.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Crystal Symphony",
      },
      {
        day: 10,
        title: "Disembark Osaka",
        location: "Osaka",
        description: "Transfer to Kansai airport.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: [
      "All-suite accommodation",
      "All dining and beverages",
      "Gratuities",
      "Shore programme",
    ],
    exclusions: ["Flights", "Japan rail extensions", "Spa"],
    extensions: [{ title: "Tokyo pre-cruise at Aman", nights: 3, priceFrom: 4200 }],
    departures: departures(["2027-03-21", "2027-04-02", "2027-04-14"], 11200, "USD", 9),
    media: { hero: images.asia, gallery: [images.asia, images.cruise] },
    terms: TERMS,
    reviews: [
      {
        author: "M. Fischer",
        rating: 4.9,
        title: "Blossom timing was perfect",
        body: "Kyoto at dawn with only our group present.",
        date: "2026-04-09",
      },
    ],
    rating: 4.9,
    reviewCount: 143,
    interests: ["Culture & heritage", "Culinary"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "CR-ANT-5501",
    title: "Antarctic Peninsula Expedition",
    subtitle: "Ushuaia round-trip with zodiac and kayak programme",
    partnerId: "crystal-cruises",
    partnerName: "Crystal Cruises",
    collection: "Polar Expeditions",
    collectionKind: "polar",
    region: "Polar",
    regionSlug: "polar",
    country: "Antarctica",
    countrySlug: "antarctica",
    cities: ["Ushuaia", "Antarctic Peninsula", "South Shetland Islands"],
    destinationSlugs: ["antarctic-peninsula"],
    durationDays: 12,
    durationNights: 11,
    priceFrom: 21500,
    currency: "USD",
    groupSizeMax: 200,
    groupStyle: "expedition",
    luxuryLevel: "ultra-luxury",
    hotels: [],
    ships: ["Crystal Endeavor"],
    rail: [],
    mealPlan: "Fully inclusive expedition dining",
    highlights: [
      "Two-to-one guest-to-expedition-staff landings",
      "Kayaking and polar plunge",
      "Penguin rookeries at Neko Harbour",
      "Onboard polar research team",
    ],
    itinerary: [
      {
        day: 1,
        title: "Embark Ushuaia",
        location: "Ushuaia",
        description: "Beagle Channel departure and expedition briefing.",
        meals: ["Dinner"],
        accommodation: "Crystal Endeavor",
      },
      {
        day: 3,
        title: "Drake Passage",
        location: "Drake Passage",
        description: "Lecture programme with ornithologists and glaciologists.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Crystal Endeavor",
      },
      {
        day: 5,
        title: "Peninsula landings",
        location: "Antarctic Peninsula",
        description: "Twice-daily zodiac landings, weather permitting.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Crystal Endeavor",
      },
      {
        day: 9,
        title: "South Shetlands",
        location: "South Shetland Islands",
        description: "Deception Island caldera and Half Moon Bay.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Crystal Endeavor",
      },
      {
        day: 12,
        title: "Disembark Ushuaia",
        location: "Ushuaia",
        description: "Charter flight to Buenos Aires.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: [
      "Charter flights Buenos Aires–Ushuaia",
      "Expedition parka and boots",
      "All landings and zodiac operations",
      "All meals and beverages",
    ],
    exclusions: ["International flights", "Insurance (mandatory)", "Kayak upgrade"],
    extensions: [{ title: "Buenos Aires at Alvear Palace", nights: 2, priceFrom: 1450 }],
    departures: departures(
      ["2026-11-22", "2026-12-18", "2027-01-20", "2027-02-08"],
      21500,
      "USD",
      11,
    ),
    media: { hero: images.polar, gallery: [images.polar, images.cruise], brochureUrl: "#brochure" },
    terms: TERMS,
    reviews: [
      {
        author: "A. Nordqvist",
        rating: 5,
        title: "Life-changing",
        body: "Eleven landings in seven days — extraordinary operations team.",
        date: "2026-02-27",
      },
    ],
    rating: 5,
    reviewCount: 88,
    interests: ["Wildlife", "Adventure"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "GA-PER-7712",
    title: "Peru: Sacred Valley & Inca Trail",
    subtitle: "Small-group trekking with luxury lodge nights",
    partnerId: "g-adventures",
    partnerName: "G Adventures",
    collection: "Small Group",
    collectionKind: "small-group",
    region: "South America",
    regionSlug: "south-america",
    country: "Peru",
    countrySlug: "peru",
    cities: ["Lima", "Cusco", "Sacred Valley", "Machu Picchu"],
    destinationSlugs: ["cusco", "machu-picchu"],
    durationDays: 9,
    durationNights: 8,
    priceFrom: 5480,
    currency: "USD",
    groupSizeMax: 16,
    groupStyle: "small-group",
    luxuryLevel: "premium",
    hotels: ["Belmond Palacio Nazarenas", "Explora Valle Sagrado"],
    ships: [],
    rail: ["Hiram Bingham to Machu Picchu"],
    mealPlan: "Breakfast daily, trek full board",
    highlights: [
      "Four-day Inca Trail with porter support",
      "Sunrise at the Sun Gate",
      "Hiram Bingham rail return",
      "Cusco ceviche masterclass",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrive Lima",
        location: "Lima",
        description: "Miraflores dinner and briefing.",
        meals: ["Dinner"],
        accommodation: "Country Club Lima",
      },
      {
        day: 3,
        title: "Sacred Valley",
        location: "Sacred Valley",
        description: "Ollantaytambo and a weaving cooperative visit.",
        meals: ["Breakfast", "Lunch"],
        accommodation: "Explora Valle Sagrado",
      },
      {
        day: 5,
        title: "Inca Trail",
        location: "Inca Trail",
        description: "Dead Woman's Pass with full porter support.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Trail camp",
      },
      {
        day: 7,
        title: "Machu Picchu",
        location: "Machu Picchu",
        description: "Sun Gate arrival and citadel tour.",
        meals: ["Breakfast", "Lunch"],
        accommodation: "Belmond Sanctuary Lodge",
      },
      {
        day: 9,
        title: "Depart Cusco",
        location: "Cusco",
        description: "Transfer for onward flights.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: [
      "Inca Trail permits and porters",
      "CEO tour leader",
      "Hiram Bingham rail",
      "All internal transfers",
    ],
    exclusions: ["International flights", "Insurance", "Optional excursions"],
    extensions: [{ title: "Amazon at Inkaterra Reserva", nights: 3, priceFrom: 1780 }],
    departures: departures(
      ["2026-09-08", "2026-10-06", "2027-04-12", "2027-05-10"],
      5480,
      "USD",
      8,
    ),
    media: { hero: images.southAmerica, gallery: [images.southAmerica, images.smallGroup] },
    terms: TERMS,
    reviews: [
      {
        author: "T. Oyelaran",
        rating: 4.7,
        title: "Superb trek support",
        body: "Porters and guides made the trail achievable and joyful.",
        date: "2026-05-14",
      },
    ],
    rating: 4.7,
    reviewCount: 302,
    interests: ["Adventure", "Culture & heritage"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "AK-ITA-1180",
    title: "Amalfi & the Aeolian Islands by Private Yacht",
    subtitle: "Naples to Taormina with a chartered crew",
    partnerId: "abercrombie-kent",
    partnerName: "Abercrombie & Kent",
    collection: "Yacht Charters",
    collectionKind: "yachts",
    region: "Europe",
    regionSlug: "europe",
    country: "Italy",
    countrySlug: "italy",
    cities: ["Naples", "Positano", "Capri", "Stromboli", "Taormina"],
    destinationSlugs: ["amalfi-coast", "capri", "sicily"],
    durationDays: 8,
    durationNights: 7,
    priceFrom: 16400,
    currency: "EUR",
    groupSizeMax: 10,
    groupStyle: "charter",
    luxuryLevel: "ultra-luxury",
    hotels: [],
    ships: ["M/Y Serenissima (charter)"],
    rail: [],
    mealPlan: "Private chef, full board with regional wines",
    highlights: [
      "Private chef and dedicated crew of six",
      "Blue Grotto before the day boats",
      "Stromboli eruptions after dark",
      "Michelin dinner in Taormina",
    ],
    itinerary: [
      {
        day: 1,
        title: "Board in Naples",
        location: "Naples",
        description: "Welcome aboard and sail to Positano.",
        meals: ["Dinner"],
        accommodation: "M/Y Serenissima",
      },
      {
        day: 3,
        title: "Capri",
        location: "Capri",
        description: "Blue Grotto at dawn and Anacapri by private car.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "M/Y Serenissima",
      },
      {
        day: 5,
        title: "Aeolian crossing",
        location: "Aeolian Islands",
        description: "Panarea swim stops and Stromboli at nightfall.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "M/Y Serenissima",
      },
      {
        day: 8,
        title: "Disembark Taormina",
        location: "Taormina",
        description: "Transfer to Catania airport.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: [
      "Full yacht charter with crew",
      "Private chef and provisioning",
      "Fuel and port fees",
      "Water toys and tenders",
    ],
    exclusions: ["Flights", "Shore dining", "Crew gratuities"],
    extensions: [{ title: "Sicily wine country at Villa Igiea", nights: 3, priceFrom: 3900 }],
    departures: departures(["2026-09-01", "2027-05-20", "2027-06-24"], 16400, "EUR", 7),
    media: { hero: images.charter, gallery: [images.charter, images.europe] },
    terms: TERMS,
    reviews: [
      {
        author: "E. Brandt",
        rating: 4.9,
        title: "Perfect summer week",
        body: "The crew anticipated everything before we asked.",
        date: "2026-06-21",
      },
    ],
    rating: 4.9,
    reviewCount: 41,
    interests: ["Beach & islands", "Yachting", "Culinary"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
];
