// DEMONSTRATION CONTENT — vertical coverage set.
//
// One flagged sample record per product line that the primary demonstration
// dataset does not yet cover, so every vertical template (river, expedition,
// rail, villas, private and tailor-made) is exercised end to end before
// partner credentials arrive. Each record is `dataSource: "demonstration"`
// and is badged in the UI; live partner records replace them verbatim.
import { images } from "../data-images";
import { DEMO_JOURNEYS } from "./demo-journeys";
import type { Journey } from "./types";

const TERMS = [
  "Deposit of 20% secures the reservation; balance due 90 days before departure.",
  "Prices are per guest based on double occupancy and exclude international air unless stated.",
  "Cancellation and amendment charges follow the operating partner's published schedule.",
];

const FAQS = [
  {
    question: "How is this journey confirmed?",
    answer:
      "Your specialist holds space with the operating partner, confirms live pricing and issues a written confirmation within 24 hours of your request.",
  },
  {
    question: "Can dates and inclusions be changed?",
    answer:
      "Yes. Every element — dates, suites, guiding, extensions and private touring — can be rewritten around you before deposit.",
  },
  {
    question: "What travel documents will I receive?",
    answer:
      "A final itinerary, supplier vouchers, insurance summary and destination briefing are issued to your account before departure.",
  },
];

function dep(dates: string[], price: number, currency: string, days: number) {
  return dates.map((date, i) => {
    const end = new Date(date);
    end.setDate(end.getDate() + days);
    const availability = (
      i === 0 ? "limited" : i === dates.length - 1 ? "waitlist" : "available"
    ) as Journey["departures"][number]["availability"];
    return {
      date,
      endDate: end.toISOString().slice(0, 10),
      price: price + i * 400,
      currency,
      availability,
      seatsRemaining: availability === "limited" ? 4 : availability === "waitlist" ? 0 : 10,
    };
  });
}

export const VERTICAL_DEMO_JOURNEYS: Journey[] = [
  {
    code: "CR-RHI-3101",
    title: "Rhine & Moselle by All-Suite River Ship",
    subtitle: "Amsterdam to Basel with private castle dinners",
    partnerId: "crystal-cruises",
    partnerName: "Crystal Cruises",
    collection: "River Cruises",
    collectionKind: "river-cruises",
    templateId: "river-cruises",
    region: "Europe",
    regionSlug: "europe",
    country: "Germany",
    countrySlug: "germany",
    cities: ["Amsterdam", "Cologne", "Rüdesheim", "Strasbourg", "Basel"],
    destinationSlugs: ["amsterdam", "cologne", "strasbourg", "basel"],
    durationDays: 9,
    durationNights: 8,
    priceFrom: 7450,
    currency: "EUR",
    groupSizeMax: 106,
    groupStyle: "charter",
    luxuryLevel: "luxury",
    hotels: [],
    ships: ["River suite ship"],
    rail: [],
    mealPlan: "All-inclusive dining with regional wine pairings",
    highlights: [
      "Butler-serviced all-suite accommodation",
      "Private dinner in a Rhine valley castle",
      "Cologne cathedral before opening",
      "Alsace vineyard tasting with the winemaker",
    ],
    itinerary: [
      {
        day: 1,
        title: "Embark Amsterdam",
        location: "Amsterdam",
        description: "Private canal cruise, then board and sail south.",
        meals: ["Dinner"],
        accommodation: "River suite",
      },
      {
        day: 3,
        title: "Cologne",
        location: "Cologne",
        description: "Cathedral access before opening and old town tasting walk.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "River suite",
      },
      {
        day: 5,
        title: "Rhine Gorge",
        location: "Rüdesheim",
        description: "Scenic cruising past the Lorelei and a castle dinner.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "River suite",
      },
      {
        day: 9,
        title: "Disembark Basel",
        location: "Basel",
        description: "Transfer to Basel airport or onward rail.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: [
      "All-suite accommodation",
      "All dining and beverages",
      "Shore excursions",
      "Wi-Fi",
    ],
    exclusions: ["International flights", "Travel insurance", "Spa treatments"],
    extensions: [{ title: "Lucerne & the Alps", nights: 3, priceFrom: 2450 }],
    departures: dep(["2026-04-18", "2026-06-13", "2026-09-05"], 7450, "EUR", 8),
    media: { hero: images.europe, gallery: [images.europe, images.cruise, images.hero] },
    waypoints: [
      { name: "Amsterdam", lat: 52.37, lng: 4.9, day: 1, kind: "start" },
      { name: "Cologne", lat: 50.94, lng: 6.96, day: 3, kind: "port" },
      { name: "Rüdesheim", lat: 49.98, lng: 7.93, day: 5, kind: "port" },
      { name: "Strasbourg", lat: 48.58, lng: 7.75, day: 7, kind: "port" },
      { name: "Basel", lat: 47.56, lng: 7.59, day: 9, kind: "end" },
    ],
    vessel: {
      name: "All-suite river ship",
      type: "River cruise vessel",
      guests: 106,
      cabins: 53,
      crew: 68,
      yearBuilt: 2023,
      amenities: ["Butler service", "Panoramic suites", "Spa", "Open bar"],
      cabinGrades: [
        {
          name: "Deluxe Suite",
          description: "Panoramic window, 26 sq m",
          priceFrom: 7450,
          available: true,
        },
        {
          name: "Owner's Suite",
          description: "Private balcony, 47 sq m",
          priceFrom: 12900,
          available: false,
        },
      ],
    },
    documents: [
      {
        title: "Deck plan",
        url: "https://worldwaytravelsgroup.com/docs/river-deck-plan.pdf",
        kind: "deck-plan",
      },
    ],
    faqs: FAQS,
    terms: TERMS,
    reviews: [],
    rating: 4.8,
    reviewCount: 164,
    interests: ["Culture & heritage", "Food & wine"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "CR-GAL-3202",
    title: "Galápagos Expedition aboard a 48-Guest Vessel",
    subtitle: "Naturalist-led landings across the western isles",
    partnerId: "crystal-cruises",
    partnerName: "Crystal Cruises",
    collection: "Expedition Cruises",
    collectionKind: "cruises-expedition",
    templateId: "expedition-cruises",
    region: "South America",
    regionSlug: "south-america",
    country: "Ecuador",
    countrySlug: "ecuador",
    cities: ["Quito", "Baltra", "Isabela", "Fernandina"],
    destinationSlugs: ["quito", "galapagos"],
    durationDays: 10,
    durationNights: 9,
    priceFrom: 11900,
    currency: "USD",
    groupSizeMax: 48,
    groupStyle: "expedition",
    luxuryLevel: "luxury",
    hotels: ["Casa Gangotena, Quito"],
    ships: ["48-guest expedition vessel"],
    rail: [],
    mealPlan: "Full board with expedition dining",
    highlights: [
      "Two naturalists per zodiac group",
      "Snorkelling with marine iguanas and sea lions",
      "Fernandina's lava fields",
      "Onboard research briefings",
    ],
    itinerary: [
      {
        day: 1,
        title: "Quito",
        location: "Quito",
        description: "Arrive and overnight in the colonial old town.",
        meals: ["Dinner"],
        accommodation: "Casa Gangotena",
      },
      {
        day: 2,
        title: "Embark Baltra",
        location: "Baltra",
        description: "Fly to the archipelago and board.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Expedition vessel",
      },
      {
        day: 5,
        title: "Isabela & Fernandina",
        location: "Isabela",
        description: "Zodiac landings, snorkelling and flightless cormorant colonies.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Expedition vessel",
      },
      {
        day: 10,
        title: "Disembark",
        location: "Baltra",
        description: "Fly to Guayaquil for onward connections.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: ["Expedition team", "All landings and equipment", "Full board", "Park fees"],
    exclusions: ["International flights", "Wetsuit hire", "Gratuities"],
    extensions: [{ title: "Amazon lodge extension", nights: 4, priceFrom: 3650 }],
    departures: dep(["2026-03-07", "2026-08-15", "2026-11-21"], 11900, "USD", 9),
    media: {
      hero: images.southAmerica,
      gallery: [images.southAmerica, images.cruise, images.hero],
    },
    waypoints: [
      { name: "Baltra", lat: -0.44, lng: -90.29, day: 2, kind: "start" },
      { name: "Isabela", lat: -0.83, lng: -91.13, day: 5, kind: "stop" },
      { name: "Fernandina", lat: -0.37, lng: -91.55, day: 6, kind: "stop" },
    ],
    vessel: {
      name: "48-guest expedition vessel",
      type: "Expedition ship",
      guests: 48,
      cabins: 24,
      crew: 32,
      iceClass: "n/a",
      amenities: ["Zodiac fleet", "Snorkel platform", "Naturalist team", "Observation deck"],
    },
    faqs: FAQS,
    terms: TERMS,
    reviews: [],
    rating: 4.9,
    reviewCount: 88,
    interests: ["Wildlife", "Adventure"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "AK-RAIL-3303",
    title: "Rajasthan by Private Rail Carriage",
    subtitle: "Delhi to Udaipur aboard a heritage luxury train",
    partnerId: "abercrombie-kent",
    partnerName: "Abercrombie & Kent",
    collection: "Rail Journeys",
    collectionKind: "rail",
    templateId: "rail",
    region: "Asia",
    regionSlug: "asia",
    country: "India",
    countrySlug: "india",
    cities: ["Delhi", "Jaipur", "Jodhpur", "Udaipur"],
    destinationSlugs: ["delhi", "jaipur", "jodhpur", "udaipur"],
    durationDays: 8,
    durationNights: 7,
    priceFrom: 9850,
    currency: "USD",
    groupSizeMax: 82,
    groupStyle: "small-group",
    luxuryLevel: "ultra-luxury",
    hotels: ["The Oberoi Udaivilas"],
    ships: [],
    rail: ["Heritage luxury train"],
    mealPlan: "Full board with two onboard restaurants",
    highlights: [
      "Private carriage with butler",
      "Amber Fort before opening",
      "Mehrangarh Fort private recital",
      "Lake Pichola sundowner",
    ],
    itinerary: [
      {
        day: 1,
        title: "Board in Delhi",
        location: "Delhi",
        description: "Champagne boarding ceremony and departure.",
        meals: ["Dinner"],
        accommodation: "Deluxe cabin",
      },
      {
        day: 3,
        title: "Jaipur",
        location: "Jaipur",
        description: "Amber Fort before opening and a private haveli lunch.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Deluxe cabin",
      },
      {
        day: 8,
        title: "Udaipur",
        location: "Udaipur",
        description: "Disembark and transfer to the lake palace hotel.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: ["Cabin accommodation", "All meals onboard", "Excursions and guiding", "Transfers"],
    exclusions: ["International flights", "Visa fees", "Spa treatments"],
    extensions: [{ title: "Taj Mahal at sunrise", nights: 2, priceFrom: 1450 }],
    departures: dep(["2026-10-09", "2026-11-13", "2027-02-05"], 9850, "USD", 7),
    media: { hero: images.india, gallery: [images.india, images.asia, images.hero] },
    waypoints: [
      { name: "Delhi", lat: 28.61, lng: 77.21, day: 1, kind: "start" },
      { name: "Jaipur", lat: 26.91, lng: 75.79, day: 3, kind: "stop" },
      { name: "Jodhpur", lat: 26.24, lng: 73.02, day: 5, kind: "stop" },
      { name: "Udaipur", lat: 24.58, lng: 73.71, day: 8, kind: "end" },
    ],
    vessel: {
      name: "Heritage luxury train",
      type: "Private rail carriage",
      guests: 82,
      cabins: 41,
      crew: 60,
      amenities: ["Butler service", "Two restaurants", "Bar carriage", "Spa carriage"],
      cabinGrades: [
        {
          name: "Deluxe cabin",
          description: "Twin or double, 12 sq m",
          priceFrom: 9850,
          available: true,
        },
        {
          name: "Presidential suite",
          description: "Two bedrooms, private lounge",
          priceFrom: 24500,
          available: true,
        },
      ],
    },
    faqs: FAQS,
    terms: TERMS,
    reviews: [],
    rating: 4.8,
    reviewCount: 121,
    interests: ["Culture & heritage", "Rail"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "AK-VIL-3404",
    title: "Private Cliffside Villa, Amalfi Coast",
    subtitle: "Six bedrooms with chef, butler and tender",
    partnerId: "abercrombie-kent",
    partnerName: "Abercrombie & Kent",
    collection: "Villas & Residences",
    collectionKind: "villas",
    templateId: "villas",
    region: "Europe",
    regionSlug: "europe",
    country: "Italy",
    countrySlug: "italy",
    cities: ["Ravello"],
    destinationSlugs: ["amalfi-coast", "ravello"],
    durationDays: 7,
    durationNights: 7,
    priceFrom: 38500,
    currency: "EUR",
    groupSizeMax: 12,
    groupStyle: "private",
    luxuryLevel: "ultra-luxury",
    hotels: ["Private villa"],
    ships: [],
    rail: [],
    mealPlan: "Private chef, breakfast and one daily meal included",
    highlights: [
      "Infinity pool above the Tyrrhenian",
      "Resident chef, butler and housekeeper",
      "Private tender for coastal days",
      "Concierge-arranged boat and dining access",
    ],
    itinerary: [],
    inclusions: [
      "Villa on exclusive use",
      "Chef and butler",
      "Daily housekeeping",
      "Airport transfers",
    ],
    exclusions: ["Flights", "Additional dining", "Tender fuel beyond four hours daily"],
    extensions: [{ title: "Capri day charter", nights: 0, priceFrom: 3200 }],
    departures: [],
    availableDates: ["2026-05-09", "2026-05-23", "2026-06-20", "2026-09-12", "2026-09-26"],
    media: { hero: images.europe, gallery: [images.europe, images.hero, images.charter] },
    waypoints: [{ name: "Ravello", lat: 40.65, lng: 14.61, kind: "start" }],
    vessel: {
      name: "Cliffside villa",
      type: "Private residence",
      guests: 12,
      bedrooms: 6,
      crew: 5,
      amenities: ["Infinity pool", "Chef's kitchen", "Gym", "Tender", "Terraced gardens"],
    },
    faqs: FAQS,
    terms: TERMS,
    reviews: [],
    rating: 4.9,
    reviewCount: 42,
    interests: ["Beach & islands", "Food & wine", "Family"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "AK-PRV-3505",
    title: "Private Japan: Tokyo, Kanazawa & Kyoto",
    subtitle: "Exclusively yours with private guides throughout",
    partnerId: "abercrombie-kent",
    partnerName: "Abercrombie & Kent",
    collection: "Private Journeys",
    collectionKind: "private",
    templateId: "private-journeys",
    region: "Asia",
    regionSlug: "asia",
    country: "Japan",
    countrySlug: "japan",
    cities: ["Tokyo", "Kanazawa", "Kyoto"],
    destinationSlugs: ["tokyo", "kanazawa", "kyoto"],
    durationDays: 12,
    durationNights: 11,
    priceFrom: 18600,
    currency: "USD",
    groupSizeMax: 6,
    groupStyle: "private",
    luxuryLevel: "ultra-luxury",
    hotels: ["Aman Tokyo", "Hoshinoya Kyoto"],
    ships: [],
    rail: ["Shinkansen Green Car"],
    mealPlan: "Breakfast daily and selected private dinners",
    highlights: [
      "Private tea ceremony with a Kyoto master",
      "After-hours temple access",
      "Kanazawa artisan workshops",
      "Sushi counter reserved privately",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrive Tokyo",
        location: "Tokyo",
        description: "Private transfer and evening orientation walk.",
        meals: [],
        accommodation: "Aman Tokyo",
      },
      {
        day: 6,
        title: "Kanazawa",
        location: "Kanazawa",
        description: "Gold-leaf and lacquer studios with the makers.",
        meals: ["Breakfast", "Lunch"],
        accommodation: "Ryokan",
      },
      {
        day: 12,
        title: "Depart Kyoto",
        location: "Kyoto",
        description: "Private transfer to Kansai airport.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: [
      "Private guiding",
      "All internal rail and transfers",
      "Accommodation",
      "Selected dining",
    ],
    exclusions: ["International flights", "Travel insurance"],
    extensions: [{ title: "Naoshima art islands", nights: 3, priceFrom: 4200 }],
    departures: [],
    availableDates: ["2026-03-28", "2026-04-11", "2026-10-17", "2026-11-07"],
    media: { hero: images.asia, gallery: [images.asia, images.hero, images.smallGroup] },
    waypoints: [
      { name: "Tokyo", lat: 35.68, lng: 139.69, day: 1, kind: "start" },
      { name: "Kanazawa", lat: 36.56, lng: 136.65, day: 6, kind: "stop" },
      { name: "Kyoto", lat: 35.01, lng: 135.77, day: 12, kind: "end" },
    ],
    faqs: FAQS,
    terms: TERMS,
    reviews: [],
    rating: 4.9,
    reviewCount: 76,
    interests: ["Culture & heritage", "Food & wine"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
  {
    code: "AK-TLR-3606",
    title: "Tailor-Made Patagonia",
    subtitle: "A framework to be rewritten around your dates and pace",
    partnerId: "abercrombie-kent",
    partnerName: "Abercrombie & Kent",
    collection: "Tailor-Made Journeys",
    collectionKind: "tailor-made",
    templateId: "tailor-made",
    region: "South America",
    regionSlug: "south-america",
    country: "Chile",
    countrySlug: "chile",
    cities: ["Santiago", "Torres del Paine", "El Calafate"],
    destinationSlugs: ["santiago", "torres-del-paine", "el-calafate"],
    durationDays: 10,
    durationNights: 9,
    priceFrom: 13400,
    currency: "USD",
    groupSizeMax: 8,
    groupStyle: "private",
    luxuryLevel: "luxury",
    hotels: ["Explora Patagonia", "Eolo Lodge"],
    ships: [],
    rail: [],
    mealPlan: "Full board in lodges",
    highlights: [
      "Private guides and 4x4 throughout",
      "Glacier navigation on Lago Grey",
      "Estancia riding with baqueanos",
      "Flexible pacing built to your fitness",
    ],
    itinerary: [
      {
        day: 1,
        title: "Santiago",
        location: "Santiago",
        description: "Arrival, wine country lunch optional.",
        meals: [],
        accommodation: "Boutique hotel",
      },
      {
        day: 4,
        title: "Torres del Paine",
        location: "Torres del Paine",
        description: "Private guided exploration at your pace.",
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Explora Patagonia",
      },
      {
        day: 10,
        title: "Depart",
        location: "El Calafate",
        description: "Transfer for onward flights.",
        meals: ["Breakfast"],
      },
    ],
    inclusions: ["Private guiding", "Lodges on full board", "Internal transfers"],
    exclusions: ["International and domestic flights", "Insurance"],
    extensions: [{ title: "Atacama Desert", nights: 4, priceFrom: 4900 }],
    departures: [],
    availableDates: ["2026-10-04", "2026-11-15", "2027-01-10", "2027-02-21"],
    media: { hero: images.southAmerica, gallery: [images.southAmerica, images.hero] },
    waypoints: [
      { name: "Santiago", lat: -33.45, lng: -70.67, day: 1, kind: "start" },
      { name: "Torres del Paine", lat: -50.94, lng: -73.4, day: 4, kind: "stop" },
      { name: "El Calafate", lat: -50.34, lng: -72.27, day: 10, kind: "end" },
    ],
    faqs: FAQS,
    terms: TERMS,
    reviews: [],
    rating: 4.8,
    reviewCount: 54,
    interests: ["Adventure", "Wildlife"],
    dataSource: "demonstration",
    updatedAt: "2026-07-01",
  },
];

/** Complete demonstration catalogue: primary set plus vertical coverage. */
export const ALL_DEMO_JOURNEYS: Journey[] = [...DEMO_JOURNEYS, ...VERTICAL_DEMO_JOURNEYS];
