// Provider-agnostic connector registry. Adding a supplier is configuration —
// no connector code has to change: the runtime reads auth, endpoints,
// capabilities, rate limits and cache policy from these records.
import type { PartnerConnectorConfig } from "./types";

export const PARTNER_CONNECTORS: PartnerConnectorConfig[] = [
  {
    id: "abercrombie-kent",
    name: "Abercrombie & Kent",
    category: "luxury-tour-operator",
    summary:
      "Ultra-luxury tailor-made and small-group journeys, Marco Polo Club departures, private jet expeditions and Egypt/Africa specialists.",
    baseUrl: "https://api.abercrombiekent.com/v1",
    auth: {
      kind: "oauth2-client-credentials",
      secrets: ["AK_CLIENT_ID", "AK_CLIENT_SECRET"],
      tokenPath: "/oauth/token",
      scope: "catalog booking",
    },
    endpoints: {
      health: "/status",
      catalog: "/journeys",
      catalogDelta: "/journeys/changes",
      availability: "/journeys/{code}/departures",
      pricing: "/journeys/{code}/pricing",
      booking: "/bookings",
      cancellation: "/bookings/{id}/cancel",
      amendment: "/bookings/{id}/amend",
      media: "/journeys/{code}/media",
      documents: "/bookings/{id}/documents",
    },
    capabilities: [
      "catalog",
      "incremental-sync",
      "availability",
      "pricing",
      "booking",
      "cancellation",
      "amendment",
      "media",
      "documents",
    ],
    collections: ["tours", "small-group", "tailor-made", "safari", "cultural", "family"],
    rateLimitPerSecond: 5,
    cacheTtlSeconds: 900,
    maxRetries: 3,
    timeoutMs: 12000,
    syncStrategy: "updated-since",
    contractStatus: "in-negotiation",
    templates: ["luxury-tours", "private-journeys", "tailor-made", "safari", "expedition-cruises"],
    feed: {
      format: "xml",
      url: "/feeds/journeys.xml",
      recordPath: "journey",
      fieldMap: {
        journeyCode: "code",
        journeyName: "title",
        shortDescription: "subtitle",
        productLine: "collection",
        regionName: "region",
        countryName: "country",
        cityList: "cities",
        days: "durationDays",
        leadInPrice: "priceFrom",
        currencyCode: "currency",
        maxGroup: "groupSizeMax",
        heroImage: "media.hero",
        galleryImages: "media.gallery",
        brochurePdf: "media.brochureUrl",
        dayByDay: "itinerary",
        departureList: "departures",
        includes: "inclusions",
        excludes: "exclusions",
        lastModified: "updatedAt",
      },
      webhookSecret: "AK_FEED_WEBHOOK_SECRET",
      refreshCron: "0 */6 * * *",
    },
  },
  {
    id: "crystal-cruises",
    name: "Crystal Cruises",
    category: "cruise-line",
    summary:
      "All-inclusive luxury ocean and expedition cruising aboard Crystal Serenity and Crystal Symphony.",
    baseUrl: "https://api.crystalcruises.com/partner/v2",
    auth: { kind: "api-key-header", secrets: ["CRYSTAL_API_KEY"], header: "X-Crystal-Key" },
    endpoints: {
      health: "/ping",
      catalog: "/voyages",
      catalogDelta: "/voyages?updatedSince={since}",
      availability: "/voyages/{code}/availability",
      pricing: "/voyages/{code}/fares",
      booking: "/reservations",
      cancellation: "/reservations/{id}/cancel",
      media: "/voyages/{code}/assets",
    },
    capabilities: [
      "catalog",
      "incremental-sync",
      "availability",
      "pricing",
      "booking",
      "cancellation",
      "media",
    ],
    collections: ["cruises", "cruises-expedition", "cruises-world"],
    rateLimitPerSecond: 8,
    cacheTtlSeconds: 600,
    maxRetries: 3,
    timeoutMs: 12000,
    syncStrategy: "updated-since",
    contractStatus: "in-negotiation",
    templates: ["ocean-cruises", "expedition-cruises", "river-cruises", "polar"],
    feed: {
      format: "json",
      url: "/feeds/voyages.json",
      recordPath: "voyages",
      fieldMap: {
        voyageCode: "code",
        voyageName: "title",
        marketingBlurb: "subtitle",
        shipName: "vessel.name",
        shipClass: "vessel.type",
        guestCapacity: "vessel.guests",
        suiteCount: "vessel.cabins",
        nights: "durationNights",
        embarkPort: "cities",
        fareFrom: "priceFrom",
        fareCurrency: "currency",
        sailings: "departures",
        portsOfCall: "waypoints",
        deckPlanUrl: "documents",
        heroImage: "media.hero",
        galleryImages: "media.gallery",
        lastUpdated: "updatedAt",
      },
      webhookSecret: "CRYSTAL_FEED_WEBHOOK_SECRET",
      refreshCron: "0 */4 * * *",
    },
  },
  {
    id: "g-adventures",
    name: "G Adventures",
    category: "adventure-operator",
    summary:
      "Small-group adventure and expedition departures with live availability via the G Adventures REST API.",
    baseUrl: "https://rest.gadventures.com",
    auth: { kind: "api-key-header", secrets: ["GADVENTURES_API_KEY"], header: "X-Application-Key" },
    endpoints: {
      health: "/",
      catalog: "/tour_dossiers",
      catalogDelta: "/departures?date_start=",
      availability: "/departures",
      pricing: "/departures/{code}",
      booking: "/bookings",
    },
    capabilities: [
      "catalog",
      "incremental-sync",
      "availability",
      "pricing",
      "booking",
      "cancellation",
    ],
    collections: ["small-group", "tours", "polar"],
    rateLimitPerSecond: 10,
    cacheTtlSeconds: 900,
    maxRetries: 3,
    timeoutMs: 10000,
    syncStrategy: "cursor",
    contractStatus: "prospective",
    docsUrl: "https://developers.gadventures.com",
  },
  {
    id: "viator",
    name: "Viator",
    category: "experiences",
    summary: "Global experiences and private touring inventory with instant confirmation.",
    baseUrl: "https://api.viator.com/partner",
    auth: { kind: "api-key-header", secrets: ["VIATOR_API_KEY"], header: "exp-api-key" },
    endpoints: {
      health: "/products/tags",
      catalog: "/products/search",
      catalogDelta: "/products/modified-since",
      availability: "/availability/schedules",
      pricing: "/availability/check",
      booking: "/bookings/cart/book",
      cancellation: "/bookings/{id}/cancel",
    },
    capabilities: [
      "catalog",
      "incremental-sync",
      "availability",
      "pricing",
      "booking",
      "cancellation",
      "media",
    ],
    collections: ["activities"],
    rateLimitPerSecond: 20,
    cacheTtlSeconds: 300,
    maxRetries: 2,
    timeoutMs: 8000,
    syncStrategy: "updated-since",
    contractStatus: "prospective",
  },
  {
    id: "tourradar",
    name: "TourRadar",
    category: "marketplace",
    summary: "Multi-day tour marketplace aggregating thousands of operators and departures.",
    baseUrl: "https://api.tourradar.com/v1",
    auth: { kind: "bearer-token", secrets: ["TOURRADAR_API_TOKEN"] },
    endpoints: {
      health: "/status",
      catalog: "/tours",
      availability: "/tours/{code}/departures",
      pricing: "/tours/{code}/prices",
      booking: "/bookings",
    },
    capabilities: ["catalog", "availability", "pricing", "booking"],
    collections: ["tours", "small-group"],
    rateLimitPerSecond: 10,
    cacheTtlSeconds: 1800,
    maxRetries: 2,
    timeoutMs: 10000,
    syncStrategy: "full",
    contractStatus: "prospective",
  },
  {
    id: "hotelbeds",
    name: "Hotelbeds",
    category: "bedbank",
    summary: "Global bedbank with luxury and boutique hotel content, transfers and activities.",
    baseUrl: "https://api.hotelbeds.com",
    auth: {
      kind: "signed-session",
      secrets: ["HOTELBEDS_API_KEY", "HOTELBEDS_SECRET"],
      header: "Api-key",
    },
    endpoints: {
      health: "/hotel-api/1.0/status",
      catalog: "/hotel-content-api/1.0/hotels",
      catalogDelta: "/hotel-content-api/1.0/hotels?lastUpdateTime={since}",
      availability: "/hotel-api/1.0/hotels",
      booking: "/hotel-api/1.0/bookings",
      cancellation: "/hotel-api/1.0/bookings/{id}",
    },
    capabilities: [
      "catalog",
      "incremental-sync",
      "availability",
      "pricing",
      "booking",
      "cancellation",
      "media",
    ],
    collections: ["hotels", "transfers", "activities"],
    rateLimitPerSecond: 15,
    cacheTtlSeconds: 600,
    maxRetries: 3,
    timeoutMs: 12000,
    syncStrategy: "updated-since",
    contractStatus: "prospective",
  },
  {
    id: "sabre",
    name: "Sabre",
    category: "gds",
    summary: "GDS air, hotel and car content with corporate fares and NDC offers.",
    baseUrl: "https://api.sabre.com",
    auth: {
      kind: "oauth2-client-credentials",
      secrets: ["SABRE_CLIENT_ID", "SABRE_CLIENT_SECRET"],
      tokenPath: "/v2/auth/token",
    },
    endpoints: {
      health: "/v1/lists/utilities/geoservices/autocomplete",
      catalog: "/v3/offers/shop",
      availability: "/v4/offers/shop",
      pricing: "/v4/shop/flights/revalidate",
      booking: "/v2.4.0/passenger/records",
      cancellation: "/v1/trip/orders/cancelBooking",
    },
    capabilities: ["availability", "pricing", "booking", "cancellation", "amendment", "documents"],
    collections: ["flights", "hotels"],
    rateLimitPerSecond: 25,
    cacheTtlSeconds: 120,
    maxRetries: 2,
    timeoutMs: 15000,
    syncStrategy: "full",
    contractStatus: "prospective",
  },
  {
    id: "amadeus",
    name: "Amadeus",
    category: "gds",
    summary:
      "Air shopping, hotel search and transfer content through Amadeus Self-Service and Enterprise APIs.",
    baseUrl: "https://api.amadeus.com",
    auth: {
      kind: "oauth2-client-credentials",
      secrets: ["AMADEUS_CLIENT_ID", "AMADEUS_CLIENT_SECRET"],
      tokenPath: "/v1/security/oauth2/token",
    },
    endpoints: {
      health: "/v1/reference-data/locations",
      catalog: "/v2/shopping/flight-offers",
      availability: "/v3/shopping/hotel-offers",
      pricing: "/v1/shopping/flight-offers/pricing",
      booking: "/v1/booking/flight-orders",
      cancellation: "/v1/booking/flight-orders/{id}",
    },
    capabilities: ["availability", "pricing", "booking", "cancellation", "documents"],
    collections: ["flights", "hotels", "transfers"],
    rateLimitPerSecond: 20,
    cacheTtlSeconds: 120,
    maxRetries: 2,
    timeoutMs: 15000,
    syncStrategy: "full",
    contractStatus: "prospective",
  },
  {
    id: "travelport",
    name: "Travelport",
    category: "gds",
    summary: "Travelport+ air content, NDC aggregation and ancillary servicing.",
    baseUrl: "https://api.travelport.com",
    auth: {
      kind: "oauth2-client-credentials",
      secrets: ["TRAVELPORT_CLIENT_ID", "TRAVELPORT_CLIENT_SECRET"],
      tokenPath: "/oauth/oauth20/token",
    },
    endpoints: {
      health: "/status",
      catalog: "/catalog/search/catalogproductofferings",
      availability: "/catalog/search",
      pricing: "/price/offers",
      booking: "/book/reservation/reservations",
      cancellation: "/book/reservation/reservations/{id}",
    },
    capabilities: ["availability", "pricing", "booking", "cancellation", "amendment"],
    collections: ["flights"],
    rateLimitPerSecond: 20,
    cacheTtlSeconds: 120,
    maxRetries: 2,
    timeoutMs: 15000,
    syncStrategy: "full",
    contractStatus: "prospective",
  },
  {
    id: "up17",
    name: "UP17 Communication Pvt Ltd",
    category: "ota-aggregation",
    summary:
      "Indian travel API aggregator for flights, hotels and buses with live inventory via header authentication.",
    baseUrl: "https://travelapi.up17.in/api",
    auth: { kind: "header-pair", secrets: ["UP17_USERNAME", "UP17_PASSWORD"] },
    endpoints: {
      health: "/airservice/rest/search",
      catalog: "/airservice/rest/search",
      availability: "/airservice/rest/search",
      pricing: "/airservice/rest/ssr",
      booking: "/airservice/rest/book",
    },
    capabilities: ["catalog", "availability", "pricing", "booking", "media"],
    collections: ["flights", "hotels", "buses"],
    rateLimitPerSecond: 5,
    cacheTtlSeconds: 120,
    maxRetries: 3,
    timeoutMs: 30000,
    syncStrategy: "full",
    contractStatus: "signed",
  },
  {
    id: "worldwayluxe",
    name: "Worldway Luxe Partner API",
    category: "marketplace",
    summary:
      "Worldway's own partner gateway — live flights, hotels, transfers, buses, private jets, wallet and concierge.",
    baseUrl: "https://worldwayluxe.com/api/public/partner",
    auth: { kind: "api-key-header", secrets: ["WORLDWAY_PARTNER_API_KEY"], header: "X-Api-Key" },
    endpoints: {
      health: "/manifest",
      catalog: "/manifest",
      availability: "/hotels/search",
      pricing: "/flights/search",
      booking: "/trip-builder/build",
    },
    capabilities: ["catalog", "availability", "pricing", "booking"],
    collections: ["flights", "hotels", "transfers", "activities", "aviation"],
    rateLimitPerSecond: 20,
    cacheTtlSeconds: 300,
    maxRetries: 2,
    timeoutMs: 15000,
    syncStrategy: "full",
    contractStatus: "signed",
  },
];

export function getConnector(id: string): PartnerConnectorConfig | null {
  return PARTNER_CONNECTORS.find((c) => c.id === id) ?? null;
}

export const PARTNER_IDS = PARTNER_CONNECTORS.map((c) => c.id);
