/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripBuilderRouteImport } from './routes/trip-builder'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneysIndexRouteImport } from './routes/journeys.index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as JourneysSlugRouteImport } from './routes/journeys.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TripBuilderRoute = TripBuilderRouteImport.update({
  id: '/trip-builder',
  path: '/trip-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysIndexRoute = JourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysSlugRoute = JourneysSlugRouteImport.update({
  id: '/journeys/$slug',
  path: '/journeys/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/membership': typeof MembershipRoute
  '/trip-builder': typeof TripBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/journeys/': typeof JourneysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/membership': typeof MembershipRoute
  '/trip-builder': typeof TripBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/blog': typeof BlogIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/journeys': typeof JourneysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/membership': typeof MembershipRoute
  '/trip-builder': typeof TripBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/journeys/': typeof JourneysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/membership'
    | '/trip-builder'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/journeys/$slug'
    | '/blog/'
    | '/destinations/'
    | '/journeys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/membership'
    | '/trip-builder'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/journeys/$slug'
    | '/blog'
    | '/destinations'
    | '/journeys'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/membership'
    | '/trip-builder'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/journeys/$slug'
    | '/blog/'
    | '/destinations/'
    | '/journeys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  MembershipRoute: typeof MembershipRoute
  TripBuilderRoute: typeof TripBuilderRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  JourneysSlugRoute: typeof JourneysSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  JourneysIndexRoute: typeof JourneysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip-builder': {
      id: '/trip-builder'
      path: '/trip-builder'
      fullPath: '/trip-builder'
      preLoaderRoute: typeof TripBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/': {
      id: '/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof JourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$slug': {
      id: '/journeys/$slug'
      path: '/journeys/$slug'
      fullPath: '/journeys/$slug'
      preLoaderRoute: typeof JourneysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  MembershipRoute: MembershipRoute,
  TripBuilderRoute: TripBuilderRoute,
  BlogSlugRoute: BlogSlugRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  JourneysSlugRoute: JourneysSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  JourneysIndexRoute: JourneysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
