/**
 * GLREP Journey Content Domain — Europe & China content data.
 *
 * Compact seeds expanded into full content documents via the factory. These
 * journeyRefs match scenicRoute ids in the GLREP registry, attaching content
 * through composition only (the registry itself is never modified).
 */

import { type BuiltJourney, type JourneySeed, buildJourney } from "./factory";

export const EUROPE_SEEDS: readonly JourneySeed[] = [
  {
    destinationSlug: "europe",
    journeyRef: "eu-r1",
    slug: "venice-simplon-orient-express",
    name: "Venice Simplon-Orient-Express",
    operatorName: "Worldway Rail",
    trainName: "Venice Simplon-Orient-Express",
    fromCity: "London",
    toCity: "Venice",
    durationDays: 2,
    summary: "The legendary London-to-Venice journey aboard restored 1920s carriages.",
    cities: ["London", "Paris", "Venice"],
    unescoNames: ["Venice and its Lagoon"],
    keywords: ["Orient Express", "luxury train Europe", "London Venice train"],
    path: [
      { lat: 51.5, lng: -0.12 },
      { lat: 48.85, lng: 2.35 },
      { lat: 45.44, lng: 12.33 },
    ],
  },
  {
    destinationSlug: "europe",
    journeyRef: "eu-r2",
    slug: "golden-eagle-danube-express",
    name: "Danube Express",
    operatorName: "Worldway Rail",
    trainName: "Danube Express",
    fromCity: "Budapest",
    toCity: "Istanbul",
    durationDays: 11,
    summary:
      "An eleven-day odyssey from Budapest to Istanbul across Central Europe and the Balkans.",
    cities: ["Budapest", "Bucharest", "Veliko Tarnovo", "Istanbul"],
    unescoNames: ["Historic Areas of Istanbul"],
    keywords: ["Danube Express", "Budapest Istanbul train", "Danube Express Europe"],
    path: [
      { lat: 47.5, lng: 19.04 },
      { lat: 44.43, lng: 26.1 },
      { lat: 41.01, lng: 28.98 },
    ],
  },
  {
    destinationSlug: "europe",
    journeyRef: "eu-r3",
    slug: "balkan-explorer",
    name: "Balkan Explorer",
    operatorName: "Worldway Rail",
    trainName: "Danube Express",
    fromCity: "Budapest",
    toCity: "Bucharest",
    durationDays: 9,
    summary: "Nine days through the heart of the Balkans by private luxury train.",
    cities: ["Budapest", "Belgrade", "Sofia", "Bucharest"],
    unescoNames: ["Rila Monastery"],
    keywords: ["Balkans luxury train", "Belgrade Sofia rail"],
    path: [
      { lat: 47.5, lng: 19.04 },
      { lat: 44.79, lng: 20.45 },
      { lat: 42.7, lng: 23.32 },
      { lat: 44.43, lng: 26.1 },
    ],
  },
  {
    destinationSlug: "europe",
    journeyRef: "eu-r4",
    slug: "grand-alpine-journey",
    name: "Grand Alpine Journey",
    operatorName: "Worldway Rail",
    trainName: "Alpine Pullman",
    fromCity: "Geneva",
    toCity: "Vienna",
    durationDays: 8,
    summary: "Eight days across the Alps from Geneva to Vienna with panoramic mountain passes.",
    cities: ["Geneva", "Zermatt", "Innsbruck", "Vienna"],
    unescoNames: ["Historic Centre of Vienna"],
    keywords: ["Alpine luxury train", "Geneva Vienna rail", "Swiss Alps train"],
    path: [
      { lat: 46.2, lng: 6.14 },
      { lat: 46.02, lng: 7.75 },
      { lat: 47.27, lng: 11.39 },
      { lat: 48.21, lng: 16.37 },
    ],
  },
  {
    destinationSlug: "europe",
    journeyRef: "eu-r5",
    slug: "italian-lakes-grand-tour",
    name: "Italian Lakes & Grand Tour",
    operatorName: "Worldway Rail",
    trainName: "Grand Tour of Europe",
    fromCity: "Milan",
    toCity: "Rome",
    durationDays: 7,
    summary: "A seven-day Italian grand tour from the lakes of Lombardy to eternal Rome.",
    cities: ["Milan", "Lake Como", "Florence", "Rome"],
    unescoNames: ["Historic Centre of Florence", "Historic Centre of Rome"],
    keywords: ["Italy luxury train", "Italian Lakes rail", "Milan Rome train"],
    path: [
      { lat: 45.46, lng: 9.19 },
      { lat: 45.99, lng: 9.26 },
      { lat: 43.77, lng: 11.26 },
      { lat: 41.9, lng: 12.5 },
    ],
  },
  {
    destinationSlug: "europe",
    journeyRef: "eu-r6",
    slug: "highlands-of-scotland",
    name: "Highlands of Scotland",
    operatorName: "Worldway Rail",
    trainName: "Royal Scotsman",
    fromCity: "Edinburgh",
    toCity: "Inverness",
    durationDays: 5,
    summary: "Five days through the Scottish Highlands aboard the Royal Scotsman.",
    cities: ["Edinburgh", "Perth", "Kyle of Lochalsh", "Inverness"],
    unescoNames: ["Old and New Towns of Edinburgh"],
    keywords: ["Royal Scotsman", "Scotland luxury train", "Highlands rail"],
    path: [
      { lat: 55.95, lng: -3.19 },
      { lat: 56.4, lng: -3.43 },
      { lat: 57.28, lng: -5.71 },
      { lat: 57.48, lng: -4.22 },
    ],
  },
  {
    destinationSlug: "europe",
    journeyRef: "eu-r7",
    slug: "spanish-andalusian-express",
    name: "Spanish Andalusian Express",
    operatorName: "Worldway Rail",
    trainName: "Al Andalus",
    fromCity: "Seville",
    toCity: "Madrid",
    durationDays: 6,
    summary: "Six days through Andalusia's Moorish cities aboard the Al Andalus.",
    cities: ["Seville", "Cordoba", "Granada", "Madrid"],
    unescoNames: ["Historic Centre of Cordoba", "Alhambra, Generalife and Albayzin, Granada"],
    keywords: ["Al Andalus train", "Spain luxury rail", "Andalusia train"],
    path: [
      { lat: 37.39, lng: -5.99 },
      { lat: 37.89, lng: -4.78 },
      { lat: 37.18, lng: -3.6 },
      { lat: 40.42, lng: -3.7 },
    ],
  },
  {
    destinationSlug: "europe",
    journeyRef: "eu-r8",
    slug: "silk-road-europe-extension",
    name: "Silk Road Europe Extension",
    operatorName: "Worldway Rail",
    trainName: "Silk Road Express",
    fromCity: "Istanbul",
    toCity: "Tbilisi",
    durationDays: 10,
    summary: "Ten days from Istanbul to Tbilisi along the western Silk Road.",
    cities: ["Istanbul", "Ankara", "Yerevan", "Tbilisi"],
    unescoNames: ["Historic Areas of Istanbul"],
    keywords: ["Silk Road train", "Istanbul Tbilisi rail", "Caucasus luxury train"],
    path: [
      { lat: 41.01, lng: 28.98 },
      { lat: 39.93, lng: 32.86 },
      { lat: 40.18, lng: 44.51 },
      { lat: 41.72, lng: 44.83 },
    ],
  },
];

export const CHINA_SEEDS: readonly JourneySeed[] = [
  {
    destinationSlug: "china",
    journeyRef: "cn-r1",
    slug: "qinghai-tibet-railway",
    name: "Qinghai–Tibet Railway",
    operatorName: "Worldway Rail",
    trainName: "Tibet Plateau Express",
    fromCity: "Xining",
    toCity: "Lhasa",
    durationDays: 2,
    summary: "The world's highest railway from Xining to Lhasa across the Tibetan plateau.",
    cities: ["Xining", "Golmud", "Lhasa"],
    unescoNames: ["Historic Ensemble of the Potala Palace, Lhasa"],
    keywords: ["Qinghai Tibet railway", "Lhasa train", "Tibet luxury rail"],
    path: [
      { lat: 36.62, lng: 101.78 },
      { lat: 36.4, lng: 94.9 },
      { lat: 29.65, lng: 91.13 },
    ],
  },
  {
    destinationSlug: "china",
    journeyRef: "cn-r2",
    slug: "ancient-china-by-private-train",
    name: "Ancient China by Private Train",
    operatorName: "Worldway Rail",
    trainName: "Shangri-La Express",
    fromCity: "Beijing",
    toCity: "Shanghai",
    durationDays: 13,
    summary: "Thirteen days across Imperial China from Beijing to Shanghai.",
    cities: ["Beijing", "Xi'an", "Chengdu", "Shanghai"],
    unescoNames: ["Mausoleum of the First Qin Emperor", "The Great Wall"],
    keywords: ["Ancient China train", "Beijing Shanghai rail", "private train China"],
    path: [
      { lat: 39.9, lng: 116.4 },
      { lat: 34.34, lng: 108.94 },
      { lat: 30.57, lng: 104.07 },
      { lat: 31.23, lng: 121.47 },
    ],
  },
  {
    destinationSlug: "china",
    journeyRef: "cn-r3",
    slug: "silk-road-expedition",
    name: "Silk Road Expedition",
    operatorName: "Worldway Rail",
    trainName: "Shangri-La Express",
    fromCity: "Xi'an",
    toCity: "Kashgar",
    durationDays: 12,
    summary: "Twelve days tracing the ancient Silk Road from Xi'an to Kashgar.",
    cities: ["Xi'an", "Dunhuang", "Turpan", "Kashgar"],
    unescoNames: ["Mogao Caves"],
    keywords: ["Silk Road expedition", "Xi'an Kashgar train", "China Silk Road rail"],
    path: [
      { lat: 34.34, lng: 108.94 },
      { lat: 40.14, lng: 94.66 },
      { lat: 42.95, lng: 89.18 },
      { lat: 39.47, lng: 75.99 },
    ],
  },
  {
    destinationSlug: "china",
    journeyRef: "cn-r4",
    slug: "dunhuang-gobi-discovery",
    name: "Dunhuang & Gobi Discovery",
    operatorName: "Worldway Rail",
    trainName: "Shangri-La Express",
    fromCity: "Dunhuang",
    toCity: "Urumqi",
    durationDays: 6,
    summary: "Six days exploring the Gobi Desert and Dunhuang's Mogao Caves.",
    cities: ["Dunhuang", "Hami", "Turpan", "Urumqi"],
    unescoNames: ["Mogao Caves"],
    keywords: ["Dunhuang train", "Gobi Desert rail", "Mogao Caves tour"],
    path: [
      { lat: 40.14, lng: 94.66 },
      { lat: 42.83, lng: 93.51 },
      { lat: 42.95, lng: 89.18 },
      { lat: 43.83, lng: 87.62 },
    ],
  },
  {
    destinationSlug: "china",
    journeyRef: "cn-r5",
    slug: "imperial-capitals",
    name: "Imperial Capitals",
    operatorName: "Worldway Rail",
    trainName: "Shangri-La Express",
    fromCity: "Beijing",
    toCity: "Xi'an",
    durationDays: 5,
    summary: "Five days between China's great imperial capitals, Beijing and Xi'an.",
    cities: ["Beijing", "Pingyao", "Xi'an"],
    unescoNames: ["The Great Wall", "Mausoleum of the First Qin Emperor"],
    keywords: ["Imperial capitals China", "Beijing Xi'an train", "Terracotta Army tour"],
    path: [
      { lat: 39.9, lng: 116.4 },
      { lat: 37.2, lng: 112.18 },
      { lat: 34.34, lng: 108.94 },
    ],
  },
  {
    destinationSlug: "china",
    journeyRef: "cn-r6",
    slug: "lhasa-himalaya-approach",
    name: "Lhasa & Himalaya Approach",
    operatorName: "Worldway Rail",
    trainName: "Tibet Plateau Express",
    fromCity: "Lhasa",
    toCity: "Shigatse",
    durationDays: 4,
    summary: "Four days from Lhasa toward the Himalaya and Tibet's second city, Shigatse.",
    cities: ["Lhasa", "Gyantse", "Shigatse"],
    unescoNames: ["Historic Ensemble of the Potala Palace, Lhasa"],
    keywords: ["Lhasa Shigatse train", "Himalaya rail", "Tibet luxury train"],
    path: [
      { lat: 29.65, lng: 91.13 },
      { lat: 28.95, lng: 89.6 },
      { lat: 29.27, lng: 88.88 },
    ],
  },
];

export const ALL_SEEDS: readonly JourneySeed[] = [...EUROPE_SEEDS, ...CHINA_SEEDS];

/** Build every seed into full content + supporting records. */
export const buildAll = (): readonly BuiltJourney[] => ALL_SEEDS.map(buildJourney);
